/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI.paraEmpleados;

import accesoAObjetos.AccesoProducto;
import accesoAObjetos.AccesoTienda;
import conexionMySQL.Conexion;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Producto;
import objetos.Tienda;

/**
 *
 * @author erikssonherlo
 */
public class backupNuevoPedido extends javax.swing.JFrame {
    String Fondo1 = "FondoNaranja5.png";
    String Logotipo = "LogoHorizontalpequeño.png";
    protected String nombreTienda;
    protected String codigoTienda;
    protected ArrayList<String> listaProductosPedido= new ArrayList<>();    //AQUI SE GUARDAN TODOS LOS DATOS DEL DETALLE PEDIDO
    
    protected ArrayList<String> tablaProductosTiendaOrigen= new ArrayList<>();   
    DefaultTableModel model = new DefaultTableModel();
     /**
     * Creates new form Interfaz
     */
    public backupNuevoPedido(String nombreTienda, String codigoTienda) {
        this.nombreTienda = nombreTienda;
        this.codigoTienda = codigoTienda;
        
        initComponents();
        //mostrarTabla();
        llenarCombos();
        model.setColumnIdentifiers(new Object[]{"Codigo Pedido", "Tienda Origen", "Tienda Destino", "Codigo Producto","Cantidad","Precio","SubTotal"});
        this.tableProductosDelPedido.setModel(model);
        cargarFondo(Fondo1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        irMenuEmpleado = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        infUsuario3 = new javax.swing.JLabel();
        inUsuario13 = new javax.swing.JLabel();
        textoUsuario1 = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        inUsuario8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        inUsuario10 = new javax.swing.JLabel();
        inUsuario11 = new javax.swing.JLabel();
        comboTienda = new javax.swing.JComboBox<>();
        buscarTienda = new javax.swing.JButton();
        inUsuario12 = new javax.swing.JLabel();
        infoTienda = new javax.swing.JLabel();
        comboNITCliente = new javax.swing.JComboBox<>();
        infUsuario2 = new javax.swing.JLabel();
        infUsuario1 = new javax.swing.JLabel();
        infCodigoPedido = new javax.swing.JLabel();
        infUsuario4 = new javax.swing.JLabel();
        infUsuario5 = new javax.swing.JLabel();
        infUsuario6 = new javax.swing.JLabel();
        infUsuario7 = new javax.swing.JLabel();
        infTotalPedido = new javax.swing.JLabel();
        infTotalAnticipo = new javax.swing.JLabel();
        textoUsuario2 = new javax.swing.JTextField();
        textoUsuario3 = new javax.swing.JTextField();
        inUsuario14 = new javax.swing.JLabel();
        infUsuario10 = new javax.swing.JLabel();
        infTotalAPagar = new javax.swing.JLabel();
        infUsuario12 = new javax.swing.JLabel();
        textoUsuario4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProductosDelPedido = new javax.swing.JTable();
        Fondo = new javax.swing.JLabel();
        infUsuario11 = new javax.swing.JLabel();
        infUsuario13 = new javax.swing.JLabel();
        infUsuario14 = new javax.swing.JLabel();
        textoUsuario5 = new javax.swing.JTextField();
        textoUsuario6 = new javax.swing.JTextField();
        textoUsuario7 = new javax.swing.JTextField();
        agregarProducto = new javax.swing.JButton();
        inUsuario9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(1, 1, 1));
        Titulo.setText("NUEVO PEDIDO");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 20, 400, 53));

        irMenuEmpleado.setBackground(new java.awt.Color(43, 46, 46));
        irMenuEmpleado.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irMenuEmpleado.setForeground(new java.awt.Color(250, 250, 244));
        irMenuEmpleado.setText("Regresar");
        irMenuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irMenuEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(irMenuEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 150, 40));

        inicio.setBackground(new java.awt.Color(43, 46, 46));
        inicio.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        inicio.setForeground(new java.awt.Color(250, 250, 244));
        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoHorizontalpequeño.png"))); // NOI18N
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 222, 66));

        cerrarSesion.setBackground(new java.awt.Color(43, 46, 46));
        cerrarSesion.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        cerrarSesion.setForeground(new java.awt.Color(250, 250, 244));
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, 150, 40));

        infUsuario3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario3.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario3.setText("Código del Pedido:");
        getContentPane().add(infUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 160, 30));

        inUsuario13.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 10)); // NOI18N
        inUsuario13.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario13.setText("AAAA-MM-DD");
        getContentPane().add(inUsuario13, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 280, 80, 30));

        textoUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario1ActionPerformed(evt);
            }
        });
        textoUsuario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoUsuario1KeyTyped(evt);
            }
        });
        getContentPane().add(textoUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 130, 30));

        agregar.setBackground(new java.awt.Color(43, 46, 46));
        agregar.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        agregar.setForeground(new java.awt.Color(250, 250, 244));
        agregar.setText("Finalizar Pedido");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 160, 40));

        inUsuario8.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 10)); // NOI18N
        inUsuario8.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario8.setText("**TODOS LOS CAMPOS SON OBLIGATORIOS");
        getContentPane().add(inUsuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 250, 20));

        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Fabricante", "Codigo del Producto", "Existencia", "Precio", "TIenda de Origen", "Descripción", "Garantia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 750, 130));

        inUsuario10.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        inUsuario10.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario10.setText("PRODUCTOS");
        getContentPane().add(inUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 80, 120, 30));

        inUsuario11.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        inUsuario11.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario11.setText("Buscar por: ");
        getContentPane().add(inUsuario11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 105, 130, 30));

        comboTienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tienda" }));
        comboTienda.setToolTipText("");
        comboTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTiendaActionPerformed(evt);
            }
        });
        getContentPane().add(comboTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 155, 150, 30));

        buscarTienda.setBackground(new java.awt.Color(43, 46, 46));
        buscarTienda.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        buscarTienda.setForeground(new java.awt.Color(250, 250, 244));
        buscarTienda.setText("Buscar");
        buscarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTiendaActionPerformed(evt);
            }
        });
        getContentPane().add(buscarTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 150, 30));

        inUsuario12.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        inUsuario12.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario12.setText("INFORMACIÓN DEL PEDIDO*:");
        getContentPane().add(inUsuario12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 290, 30));

        infoTienda.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 14)); // NOI18N
        infoTienda.setText("Nombre Tienda");
        getContentPane().add(infoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        comboNITCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIT" }));
        comboNITCliente.setToolTipText("");
        comboNITCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNITClienteActionPerformed(evt);
            }
        });
        getContentPane().add(comboNITCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 80, 30));

        infUsuario2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario2.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario2.setText("Ingrese la Fecha de Hoy:");
        getContentPane().add(infUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 210, 30));

        infUsuario1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario1.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario1.setText("Ingrese el NIT del Cliente:");
        getContentPane().add(infUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 230, 30));

        infCodigoPedido.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infCodigoPedido.setForeground(new java.awt.Color(4, 2, 2));
        infCodigoPedido.setText("No.");
        getContentPane().add(infCodigoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 60, 30));

        infUsuario4.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario4.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario4.setText("Anticipo Efectivo:");
        getContentPane().add(infUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 150, 30));

        infUsuario5.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario5.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario5.setText("Anticipo Credito:");
        getContentPane().add(infUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 150, 30));

        infUsuario6.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario6.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario6.setText("Anticipo Total:");
        getContentPane().add(infUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 130, 30));

        infUsuario7.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario7.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario7.setText("Total del Pedido:");
        getContentPane().add(infUsuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 140, 30));

        infTotalPedido.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infTotalPedido.setForeground(new java.awt.Color(4, 2, 2));
        infTotalPedido.setText("000.00");
        getContentPane().add(infTotalPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 80, 30));

        infTotalAnticipo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infTotalAnticipo.setForeground(new java.awt.Color(4, 2, 2));
        infTotalAnticipo.setText("000.00");
        getContentPane().add(infTotalAnticipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 90, 30));

        textoUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario2ActionPerformed(evt);
            }
        });
        textoUsuario2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoUsuario2KeyTyped(evt);
            }
        });
        getContentPane().add(textoUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 320, 80, 30));

        textoUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario3ActionPerformed(evt);
            }
        });
        textoUsuario3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoUsuario3KeyTyped(evt);
            }
        });
        getContentPane().add(textoUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 80, 30));

        inUsuario14.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        inUsuario14.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario14.setText("INFORMACIÓN DE LOS PRODUCTOS:");
        getContentPane().add(inUsuario14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 360, 30));

        infUsuario10.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario10.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario10.setText("Pago Total:");
        getContentPane().add(infUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 130, 30));

        infTotalAPagar.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infTotalAPagar.setForeground(new java.awt.Color(4, 2, 2));
        infTotalAPagar.setText("000.00");
        getContentPane().add(infTotalAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 355, 80, 30));

        infUsuario12.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario12.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario12.setText("Total a Pagar:");
        getContentPane().add(infUsuario12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 355, 130, 30));

        textoUsuario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario4ActionPerformed(evt);
            }
        });
        textoUsuario4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoUsuario4KeyTyped(evt);
            }
        });
        getContentPane().add(textoUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 360, 80, 30));

        tableProductosDelPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Pedido", "Tienda Origen", "Tienda Destino", "Codigo del Producto", "Cantidad", "Precio", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableProductosDelPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductosDelPedidoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableProductosDelPedido);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 750, 120));

        Fondo.setBackground(new java.awt.Color(59, 55, 51));
        Fondo.setText("Fondo General");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 250));

        infUsuario11.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario11.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario11.setText("Cantidad:");
        getContentPane().add(infUsuario11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 80, 30));

        infUsuario13.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario13.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario13.setText("Código del Producto:");
        getContentPane().add(infUsuario13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 180, 30));

        infUsuario14.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario14.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario14.setText("Precio:");
        getContentPane().add(infUsuario14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 70, 30));

        textoUsuario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario5ActionPerformed(evt);
            }
        });
        textoUsuario5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoUsuario5KeyTyped(evt);
            }
        });
        getContentPane().add(textoUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 110, 30));

        textoUsuario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario6ActionPerformed(evt);
            }
        });
        textoUsuario6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoUsuario6KeyTyped(evt);
            }
        });
        getContentPane().add(textoUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 80, 30));

        textoUsuario7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario7ActionPerformed(evt);
            }
        });
        textoUsuario7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoUsuario7KeyTyped(evt);
            }
        });
        getContentPane().add(textoUsuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 80, 30));

        agregarProducto.setBackground(new java.awt.Color(43, 46, 46));
        agregarProducto.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        agregarProducto.setForeground(new java.awt.Color(250, 250, 244));
        agregarProducto.setText("Agregar Producto Al Pedido");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(agregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 240, 40));

        inUsuario9.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 10)); // NOI18N
        inUsuario9.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario9.setText("*DEBE COMPLETAR LA PARTE INFORMATIVA ANTES DE AGREGAR UN PRODUCTO");
        getContentPane().add(inUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 650, 440, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void mostrarTabla(String tiendaOrigen) {
        DefaultTableModel model = new DefaultTableModel();
        Conexion conexion = new Conexion();
        ResultSet rs = conexion.getTabla("SELECT * FROM EXISTENCIA_PRODUCTO WHERE Codigo_Tienda= '"+tiendaOrigen+"'");
        model.setColumnIdentifiers(new Object[]{"Nombre", "Fabricante", "Codigo Producto", "Existencia","Precio","Tienda Origen","Descripcion","Garantia"});
        
        try {
            while (rs.next()) {
               
                model.addRow(new Object[]{rs.getString("Nombre"), rs.getString("Fabricante"), rs.getString("Codigo_Producto"), rs.getInt("Precio"),rs.getString("Precio"),rs.getString("Codigo_Tienda"),rs.getString("Descripcion"),rs.getInt("Garantia")});
            }
            tableProductos.setModel(model);
        } catch (SQLException e) {
        }
    }

 
 
    private void llenarCombos() {
        
        Conexion conexion = new Conexion();
        ResultSet rs = conexion.getTabla("SELECT Nombre,Codigo_Tienda FROM TIENDA WHERE Codigo_Tienda <> '"+codigoTienda+"'");
            try {
            while (rs.next()) {
                comboTienda.addItem(rs.getString(1));
                tablaProductosTiendaOrigen.add(rs.getString(2));
                }

        } catch (SQLException e) {

        }
     
        ResultSet rs1 = conexion.getTabla("SELECT NIT FROM CLIENTE");
            try {
            while (rs1.next()) {
                comboNITCliente.addItem(rs1.getString(1));
                
                }

        } catch (SQLException e) {

        }
    }
    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
              // TODO add your handling code here:
             ElegirTienda eleccion = new ElegirTienda();
            eleccion.setVisible(true);
            this.setVisible(false); 
              
    }//GEN-LAST:event_inicioActionPerformed

    private void irMenuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irMenuEmpleadoActionPerformed
            MenuEmpleado eleccion = new MenuEmpleado(nombreTienda, codigoTienda);
              eleccion.setVisible(true);
              this.setVisible(false);
    }//GEN-LAST:event_irMenuEmpleadoActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        Inicio iniciarInterfaz = new Inicio();
        iniciarInterfaz.setVisible(true);    
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void textoUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario1ActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        
        String nombre = textoUsuario1.getText();
        String fabricante=textoUsuario2.getText();
        String codigo =textoUsuario3.getText();
        int existencia = Integer.parseInt(textoUsuario4.getText());
        Double precio = Double.parseDouble(textoUsuario5.getText());
        String descripcion = textoUsuario6.getText();
        int garantia = Integer.parseInt(textoUsuario7.getText());
        if (nombre.equals("") || fabricante.equals("") || codigo.equals("") || existencia==0 || precio==0){
            JOptionPane.showMessageDialog(null, "Ingrese todos los Campos Obligatorios");
        }else{
            Producto nuevo = new Producto(nombre, fabricante, codigo, existencia, precio, codigoTienda,descripcion,garantia);
            accesoAObjetos.AccesoProducto llenar = new AccesoProducto();
             if(!llenar.insertarProducto(nuevo))
        {   JOptionPane.showMessageDialog(null, "No se puedo Ingresar la tienda "+nombre+"\ndebido a que tiene datos repetidos con otra Tienda ingresada en la Base de Datos");
        }else{
            JOptionPane.showMessageDialog(null, "Producto Agregado Exitosamente");
            MenuEmpleado eleccion = new MenuEmpleado(nombreTienda,codigoTienda);
              eleccion.setVisible(true);
              this.setVisible(false);
              this.dispose();
        }
        }
        
    }//GEN-LAST:event_agregarActionPerformed

    private void tableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductosMouseClicked
        int seleccion = tableProductos.getSelectedRow();
        textoUsuario5.setText(tableProductos.getValueAt(seleccion, 2).toString());
        textoUsuario7.setText(tableProductos.getValueAt(seleccion, 4).toString());
        
        
    }//GEN-LAST:event_tableProductosMouseClicked

    private void comboTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTiendaActionPerformed

    private void buscarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTiendaActionPerformed
        if(comboTienda.getSelectedIndex()!=0){
            mostrarTabla(tablaProductosTiendaOrigen.get(comboTienda.getSelectedIndex()-1));
          //MenuEmpleado accesarAlMenu = new MenuEmpleado(comboTienda.getItemAt(comboTienda.getSelectedIndex()),tablaTienda.get(comboTienda.getSelectedIndex()-1));
        //accesarAlMenu.setVisible(true);
        
        } else
        {
            JOptionPane.showMessageDialog(null, "Por favor, Seleccione una Tienda");
                   
        }// TODO add your handling code here:
    }//GEN-LAST:event_buscarTiendaActionPerformed

    private void comboNITClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNITClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNITClienteActionPerformed

    private void textoUsuario1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUsuario1KeyTyped
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='-'){
       evt.consume();
   } 
        if(evt.getKeyChar()=='-'&&textoUsuario1.getText().contains("--")){
      evt.consume();
       }
    }//GEN-LAST:event_textoUsuario1KeyTyped

    private void textoUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario2ActionPerformed

    private void textoUsuario2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUsuario2KeyTyped
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&textoUsuario2.getText().contains(".")){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario2KeyTyped

    private void textoUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario3ActionPerformed

    private void textoUsuario3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUsuario3KeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&textoUsuario3.getText().contains(".")){
            evt.consume();
        }   
    }//GEN-LAST:event_textoUsuario3KeyTyped

    private void textoUsuario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario4ActionPerformed

    private void textoUsuario4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUsuario4KeyTyped
if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&textoUsuario4.getText().contains(".")){
            evt.consume();
        }                   // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario4KeyTyped

    private void tableProductosDelPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductosDelPedidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableProductosDelPedidoMouseClicked

    private void textoUsuario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario5ActionPerformed

    private void textoUsuario5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUsuario5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario5KeyTyped

    private void textoUsuario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario6ActionPerformed

    private void textoUsuario6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUsuario6KeyTyped
        // TODO add your handling code here:
         char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }   
    }//GEN-LAST:event_textoUsuario6KeyTyped

    private void textoUsuario7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario7ActionPerformed

    private void textoUsuario7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUsuario7KeyTyped
if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&textoUsuario7.getText().contains(".")){
            evt.consume();
        }           // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario7KeyTyped

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        //BLOQUE DE OPERACIONES
        int codigoPedido=28;//HACER FUNCION QUE DEVUELVA UN ENTERO, DONDE SE OBTENGA EL CODIGO DEL PEDIDO MAS GRANDE
        
        String tiendaOrigen = tablaProductosTiendaOrigen.get(comboTienda.getSelectedIndex()-1);
        String codigoProducto = textoUsuario5.getText();
        int cantidad = Integer.parseInt(textoUsuario6.getText());
        Double precio = Double.parseDouble(textoUsuario7.getText());
        double subTotal =cantidad*precio;
        double total = 0;
        total =+subTotal;
        
        //BLOQUE DE STRINGS PARA EL ARRAYLIST
        String infoTotal = Double.toString(total);
        String infoCodigoPedido = Integer.toString(codigoPedido);
        String infoSubTotal = Double.toString(subTotal);
        
        
        
        //ACCIONES DE MUESTRA DE INFORMACION
       infCodigoPedido.setText(infoCodigoPedido);
        
        
        
        if (tiendaOrigen.equals("") || codigoProducto.equals("") || cantidad==0 || precio==0){
            JOptionPane.showMessageDialog(null, "Ingrese todos los Campos Obligatorios");
        }else{
              model.addRow(new Object[]{codigoPedido, tiendaOrigen, codigoTienda, codigoProducto,cantidad,precio,subTotal});
       
        //    mostrarTablaProductosDelPedido(codigoPedido, tiendaOrigen, codigoTienda, codigoProducto, cantidad, precio, subTotal);
        //        comboTienda.getItemAt(comboTienda.getSelectedIndex()),tablaTienda.get(comboTienda.getSelectedIndex()-1)
        //AGREGAR TODOS LOS CAMPOS DEL DETALLE PEDIDO
        listaProductosPedido.add(infoCodigoPedido);         
        listaProductosPedido.add(tiendaOrigen);             
        listaProductosPedido.add(codigoTienda);
        listaProductosPedido.add(codigoProducto);
        listaProductosPedido.add(textoUsuario6.getText()); //CANTIDAD
        listaProductosPedido.add(textoUsuario7.getText()); //PRECIO
        listaProductosPedido.add(infoSubTotal);
        
        //VISUALIZACION EN CONSOLA
        for (int i=0; i<listaProductosPedido.size();i=i+7)
        {
        System.out.println(listaProductosPedido.get(i));
        System.out.println(listaProductosPedido.get(i+1));
        System.out.println(listaProductosPedido.get(i+2));
        System.out.println(listaProductosPedido.get(i+3));
        System.out.println(listaProductosPedido.get(i+4));
        System.out.println(listaProductosPedido.get(i+5));
        System.out.println(listaProductosPedido.get(i+6));
        System.out.println(listaProductosPedido.get(i+7));
        
        
        }
        
        //LIMPIAR LA INTERFAZ
        textoUsuario5.setText("");
        textoUsuario6.setText("");
        textoUsuario7.setText("");
        infTotalPedido.setText(infoTotal);
        
         }
    }//GEN-LAST:event_agregarProductoActionPerformed

    /**
     */
    public void cargarFondo(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(Fondo.getWidth(), Fondo.getHeight(), Image.SCALE_DEFAULT));
        Fondo.setIcon(imageIconFinal);
    }
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Fondo;
    public javax.swing.JLabel Titulo;
    public javax.swing.JButton agregar;
    public javax.swing.JButton agregarProducto;
    public javax.swing.JButton buscarTienda;
    public javax.swing.JButton cerrarSesion;
    private javax.swing.JComboBox<String> comboNITCliente;
    private javax.swing.JComboBox<String> comboTienda;
    public javax.swing.JLabel inUsuario10;
    public javax.swing.JLabel inUsuario11;
    public javax.swing.JLabel inUsuario12;
    public javax.swing.JLabel inUsuario13;
    public javax.swing.JLabel inUsuario14;
    public javax.swing.JLabel inUsuario8;
    public javax.swing.JLabel inUsuario9;
    public javax.swing.JLabel infCodigoPedido;
    public javax.swing.JLabel infTotalAPagar;
    public javax.swing.JLabel infTotalAnticipo;
    public javax.swing.JLabel infTotalPedido;
    public javax.swing.JLabel infUsuario1;
    public javax.swing.JLabel infUsuario10;
    public javax.swing.JLabel infUsuario11;
    public javax.swing.JLabel infUsuario12;
    public javax.swing.JLabel infUsuario13;
    public javax.swing.JLabel infUsuario14;
    public javax.swing.JLabel infUsuario2;
    public javax.swing.JLabel infUsuario3;
    public javax.swing.JLabel infUsuario4;
    public javax.swing.JLabel infUsuario5;
    public javax.swing.JLabel infUsuario6;
    public javax.swing.JLabel infUsuario7;
    private javax.swing.JLabel infoTienda;
    public javax.swing.JButton inicio;
    public javax.swing.JButton irMenuEmpleado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTable tableProductosDelPedido;
    public javax.swing.JTextField textoUsuario1;
    public javax.swing.JTextField textoUsuario2;
    public javax.swing.JTextField textoUsuario3;
    public javax.swing.JTextField textoUsuario4;
    public javax.swing.JTextField textoUsuario5;
    public javax.swing.JTextField textoUsuario6;
    public javax.swing.JTextField textoUsuario7;
    // End of variables declaration//GEN-END:variables
}
