/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI.paraEmpleados;
import cargaArchivos.LecturaDeArchivo;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author erikssonherlo
 */
public class CargaArchivo extends javax.swing.JFrame {
    String Fondo1 = "FondoNaranja5.png";
    String Logotipo = "Logo.png";
    javax.swing.JFileChooser buscar = new JFileChooser();
    //LecturaDeArchivo file = new LecturaDeArchivo();
    /**
     * Creates new form Interfaz
     */
    public CargaArchivo() {
        initComponents();
        cargarFondo(Fondo1);
        cargarLogotipo(Logotipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        instruccionesUsuario = new javax.swing.JLabel();
        direccionArchivo = new javax.swing.JTextField();
        agregarArchivo = new javax.swing.JButton();
        buscarArchivo = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        instruccionesUsuario1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setText("Logo");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 20, 225, 225));

        titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(1, 1, 1));
        titulo.setText("Carga de Archivos");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 260, -1, 53));

        instruccionesUsuario.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        instruccionesUsuario.setForeground(new java.awt.Color(4, 2, 2));
        instruccionesUsuario.setText("Ingrese el Archivo de Texto:");
        getContentPane().add(instruccionesUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 290, 30));

        direccionArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(direccionArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 290, 30));

        agregarArchivo.setBackground(new java.awt.Color(43, 46, 46));
        agregarArchivo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        agregarArchivo.setForeground(new java.awt.Color(250, 250, 244));
        agregarArchivo.setText("Cargar Archivo");
        agregarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(agregarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 435, 290, 40));

        buscarArchivo.setBackground(new java.awt.Color(43, 46, 46));
        buscarArchivo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        buscarArchivo.setForeground(new java.awt.Color(250, 250, 244));
        buscarArchivo.setText("Buscar Archivo");
        buscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(buscarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 290, 40));

        salir.setBackground(new java.awt.Color(43, 46, 46));
        salir.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        salir.setForeground(new java.awt.Color(250, 250, 244));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 290, 40));

        instruccionesUsuario1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        instruccionesUsuario1.setForeground(new java.awt.Color(4, 2, 2));
        instruccionesUsuario1.setText("Nombre del Archivo de Texto:");
        getContentPane().add(instruccionesUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 290, 30));

        fondo.setBackground(new java.awt.Color(59, 55, 51));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarArchivoActionPerformed
       
       
       buscar.showOpenDialog(buscar);
     direccionArchivo.setText(buscar.getSelectedFile().getName());
       /* JFileChooser file = new JFileChooser();
        file = new JFileChooser("/home/erikssonherlo/NetBeansProjects/SistemaIntelaf");
        file.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int returnVal = file.showOpenDialog(this);
      
        //FileFilter filter = new FileNameExtensionFilter("Archivo de Texto (.txt)",".txt");
        //file.addChoosableFileFilter(filter);
         if(returnVal == JFileChooser.APPROVE_OPTION) {
            direccionArchivo.setText(file.getSelectedFile().getName());
            buscarArchivo.setEnabled(false);
         } else {
            buscarArchivo.setEnabled(false);       
         }         */   
    }//GEN-LAST:event_buscarArchivoActionPerformed

    private void agregarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarArchivoActionPerformed
        
        File f;
          try {
            String path = buscar.getSelectedFile().getAbsolutePath();
            String lectura = "";
            f = new File(path);
            LecturaDeArchivo leer = new LecturaDeArchivo();
                    leer.muestraContenido(f);
            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_agregarArchivoActionPerformed

    private void direccionArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionArchivoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    /**
     */
    public void cargarFondo(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(imageIconFinal);
    }
        public void cargarLogotipo(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_DEFAULT));
        logo.setIcon(imageIconFinal);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton agregarArchivo;
    public javax.swing.JButton buscarArchivo;
    public javax.swing.JTextField direccionArchivo;
    public javax.swing.JLabel fondo;
    public javax.swing.JLabel instruccionesUsuario;
    public javax.swing.JLabel instruccionesUsuario1;
    public javax.swing.JLabel logo;
    public javax.swing.JButton salir;
    public javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
