/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI.paraEmpleados;

import conexionMySQL.Conexion;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author erikssonherlo
 */
public class ElegirTienda extends javax.swing.JFrame {
    protected ArrayList<String> tablaTienda= new ArrayList<>();
    String Fondo1 = "FondoNaranja5.png";
    String Logotipo = "Logo.png";
    /**
     * Creates new form Interfaz
     */
    public ElegirTienda(){
        initComponents();
        llenarCombo();
        cargarFondo(Fondo1);
        cargarLogotipo(Logotipo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        instruccionesUsuario = new javax.swing.JLabel();
        Ingresar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        comboTienda = new javax.swing.JComboBox<>();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setText("Logo");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 20, 225, 225));

        titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(1, 1, 1));
        titulo.setText("TIENDA");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 260, 200, 53));

        instruccionesUsuario.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        instruccionesUsuario.setForeground(new java.awt.Color(4, 2, 2));
        instruccionesUsuario.setText("Elija la Tienda a la que desea acceder:");
        getContentPane().add(instruccionesUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 360, 30));

        Ingresar.setBackground(new java.awt.Color(43, 46, 46));
        Ingresar.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(250, 250, 244));
        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        getContentPane().add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 435, 290, 40));

        salir.setBackground(new java.awt.Color(43, 46, 46));
        salir.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        salir.setForeground(new java.awt.Color(250, 250, 244));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 290, 40));

        comboTienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:" }));
        comboTienda.setToolTipText("");
        comboTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTiendaActionPerformed(evt);
            }
        });
        getContentPane().add(comboTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 170, 40));

        fondo.setBackground(new java.awt.Color(59, 55, 51));
        fondo.setText("Fondo General");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        Inicio iniciarInterfaz = new Inicio();
        iniciarInterfaz.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        if(comboTienda.getSelectedIndex()!=0){
        MenuEmpleado accesarAlMenu = new MenuEmpleado(comboTienda.getItemAt(comboTienda.getSelectedIndex()),tablaTienda.get(comboTienda.getSelectedIndex()-1));
        accesarAlMenu.setVisible(true);
        this.setVisible(false);
        } else
        {
            JOptionPane.showMessageDialog(null, "Por favor, Seleccione una Tienda");
                   
        }
    }//GEN-LAST:event_IngresarActionPerformed
private void llenarCombo() {
        
        Conexion conexion = new Conexion();
        ResultSet rs = conexion.getTabla("SELECT Nombre,Codigo_Tienda FROM TIENDA");
        try {
            while (rs.next()) {
                comboTienda.addItem(rs.getString(1));
                tablaTienda.add(rs.getString(2));
            }

        } catch (Exception e) {

        }
    }
    private void comboTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTiendaActionPerformed

    /**
     */
    public void cargarFondo(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(imageIconFinal);
    }
        public void cargarLogotipo(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_DEFAULT));
        logo.setIcon(imageIconFinal);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Ingresar;
    private javax.swing.JComboBox<String> comboTienda;
    public javax.swing.JLabel fondo;
    public javax.swing.JLabel instruccionesUsuario;
    public javax.swing.JLabel logo;
    public javax.swing.JButton salir;
    public javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
