/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI.paraEmpleados;

import backend.InicioUsuario;
import com.mycompany.UI.paraUsuarios.MenuCliente;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import objetos.Cliente;
import objetos.Empleado;

/**
 *
 * @author erikssonherlo
 */
public class Inicio extends javax.swing.JFrame {
    String Fondo1 = "FondoNaranja5.png";
    String Logotipo = "Logo.png";
    /**
     * Creates new form Interfaz
     */
    public Inicio() {
        initComponents();
        cargarFondo(Fondo1);
        cargarLogotipo(Logotipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        instruccionesUsuario = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JTextField();
        Ingresar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setText("Logo");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 20, 225, 225));

        titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(1, 1, 1));
        titulo.setText("INICIAR SESIÓN");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 420, 53));

        instruccionesUsuario.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        instruccionesUsuario.setForeground(new java.awt.Color(4, 2, 2));
        instruccionesUsuario.setText("Ingrese su NIT / Codigo de Empleado:");
        getContentPane().add(instruccionesUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 330, 350, 30));

        textoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(textoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 290, 30));

        Ingresar.setBackground(new java.awt.Color(43, 46, 46));
        Ingresar.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(250, 250, 244));
        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        getContentPane().add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 435, 290, 40));

        salir.setBackground(new java.awt.Color(43, 46, 46));
        salir.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        salir.setForeground(new java.awt.Color(250, 250, 244));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 290, 40));

        fondo.setBackground(new java.awt.Color(59, 55, 51));
        fondo.setText("Fondo General");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        String codigo =textoUsuario.getText();
        InicioUsuario user1 = new InicioUsuario();
        Empleado empleado = user1.iniciarSesionEmpleado(codigo);
        InicioUsuario user2 = new InicioUsuario();
        Cliente cliente = user2.iniciarSesionCliente(codigo);
        if(empleado != null)
        {
            JOptionPane.showMessageDialog(null, "Bienvenido Empleado "+empleado.getNombre());
        ElegirTienda accesarAlMenu = new ElegirTienda();
        accesarAlMenu.setVisible(true);
        this.setVisible(false);
            
            
        }else if(cliente != null)
        {
            JOptionPane.showMessageDialog(null, "Bienvenido  "+cliente.getNombre()+" al Software de Intelaf");
            
        MenuCliente accesarAlMenu = new MenuCliente(cliente.getNombre(), cliente.getNIT());
        accesarAlMenu.setVisible(true);
        this.setVisible(false);   
        
        }
        else if(textoUsuario.getText()==""){
            JOptionPane.showMessageDialog(null, "Ingrese su Codigo para Iniciar Sesión");
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Ingrese un Codigo de Inicio de Sesión correcto");
        
        }
        
    }//GEN-LAST:event_IngresarActionPerformed

    private void textoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textoUsuarioActionPerformed

    /**
     */
    public void cargarFondo(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(imageIconFinal);
    }
        public void cargarLogotipo(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_DEFAULT));
        logo.setIcon(imageIconFinal);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Ingresar;
    public javax.swing.JLabel fondo;
    public javax.swing.JLabel instruccionesUsuario;
    public javax.swing.JLabel logo;
    public javax.swing.JButton salir;
    public javax.swing.JTextField textoUsuario;
    public javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
