/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI.paraEmpleados;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author erikssonherlo
 */
public class MenuVisualizarInformacion extends javax.swing.JFrame {
    String Fondo1 = "FondoNaranja5.png";
    String Logotipo = "LogoHorizontalpequeño.png";
    protected String nombreTienda;
    protected String codigoTienda;
    /**
     * Creates new form Interfaz
     */
    public MenuVisualizarInformacion(String nombreTienda, String codigoTienda) {
        this.nombreTienda = nombreTienda;
        this.codigoTienda = codigoTienda;
        
        initComponents();
        infoTienda.setText(nombreTienda);
        cargarFondo(Fondo1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        inicio = new javax.swing.JButton();
        visualizarTiendas = new javax.swing.JButton();
        visualizarProductos = new javax.swing.JButton();
        visualizarEmpleado = new javax.swing.JButton();
        visualizarClientes = new javax.swing.JButton();
        irMenuEmpleado = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        infoTienda = new javax.swing.JLabel();
        visualizarNuevoTiempo = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(1, 1, 1));
        Titulo.setText("VISUALIZAR INFORMACIÓN");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 120, 530, 53));

        inicio.setBackground(new java.awt.Color(43, 46, 46));
        inicio.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        inicio.setForeground(new java.awt.Color(250, 250, 244));
        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoHorizontalpequeño.png"))); // NOI18N
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 222, 91));

        visualizarTiendas.setBackground(new java.awt.Color(43, 46, 46));
        visualizarTiendas.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        visualizarTiendas.setForeground(new java.awt.Color(250, 250, 244));
        visualizarTiendas.setText("Ver Tiendas");
        visualizarTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarTiendasActionPerformed(evt);
            }
        });
        getContentPane().add(visualizarTiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 175, 290, 40));

        visualizarProductos.setBackground(new java.awt.Color(43, 46, 46));
        visualizarProductos.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        visualizarProductos.setForeground(new java.awt.Color(250, 250, 244));
        visualizarProductos.setText("Ver Productos");
        visualizarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarProductosActionPerformed(evt);
            }
        });
        getContentPane().add(visualizarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 285, 290, 40));

        visualizarEmpleado.setBackground(new java.awt.Color(43, 46, 46));
        visualizarEmpleado.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        visualizarEmpleado.setForeground(new java.awt.Color(250, 250, 244));
        visualizarEmpleado.setText("Ver Empleados");
        visualizarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(visualizarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 340, 290, 40));

        visualizarClientes.setBackground(new java.awt.Color(43, 46, 46));
        visualizarClientes.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        visualizarClientes.setForeground(new java.awt.Color(250, 250, 244));
        visualizarClientes.setText("Ver Clientes");
        visualizarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarClientesActionPerformed(evt);
            }
        });
        getContentPane().add(visualizarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 395, 290, 40));

        irMenuEmpleado.setBackground(new java.awt.Color(43, 46, 46));
        irMenuEmpleado.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irMenuEmpleado.setForeground(new java.awt.Color(250, 250, 244));
        irMenuEmpleado.setText("Regresar Al Menú Anterior");
        irMenuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irMenuEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(irMenuEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 450, 290, 40));

        cerrarSesion.setBackground(new java.awt.Color(43, 46, 46));
        cerrarSesion.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        cerrarSesion.setForeground(new java.awt.Color(250, 250, 244));
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 505, 290, 40));

        infoTienda.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 14)); // NOI18N
        infoTienda.setText("Nombre Tienda");
        getContentPane().add(infoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 102, -1, 20));

        visualizarNuevoTiempo.setBackground(new java.awt.Color(43, 46, 46));
        visualizarNuevoTiempo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        visualizarNuevoTiempo.setForeground(new java.awt.Color(250, 250, 244));
        visualizarNuevoTiempo.setText("Ver Tiempo entre Tiendas");
        visualizarNuevoTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarNuevoTiempoActionPerformed(evt);
            }
        });
        getContentPane().add(visualizarNuevoTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 230, 290, 40));

        Fondo.setBackground(new java.awt.Color(59, 55, 51));
        Fondo.setText("Fondo General");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
            ElegirTienda eleccion = new ElegirTienda();
            eleccion.setVisible(true);
            this.setVisible(false);              // TODO add your handling code here:
              
              
    }//GEN-LAST:event_inicioActionPerformed

    private void irMenuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irMenuEmpleadoActionPerformed
            MenuEmpleado eleccion = new MenuEmpleado(nombreTienda,codigoTienda);
              eleccion.setVisible(true);
              this.setVisible(false);
    }//GEN-LAST:event_irMenuEmpleadoActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
    Inicio iniciarInterfaz = new Inicio();
        iniciarInterfaz.setVisible(true);   
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void visualizarTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarTiendasActionPerformed
        VisualizarTienda eleccion = new VisualizarTienda(nombreTienda,codigoTienda);
        eleccion.setVisible(true);
              this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_visualizarTiendasActionPerformed

    private void visualizarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarProductosActionPerformed
       VisualizarProductos eleccion = new VisualizarProductos(nombreTienda, codigoTienda);
       eleccion.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_visualizarProductosActionPerformed

    private void visualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarEmpleadoActionPerformed
        VisualizarEmpleados eleccion = new VisualizarEmpleados(nombreTienda, codigoTienda);
        eleccion.setVisible(true);
        this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_visualizarEmpleadoActionPerformed

    private void visualizarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarClientesActionPerformed
        VisualizarClientes eleccion = new VisualizarClientes(nombreTienda, codigoTienda);
        eleccion.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_visualizarClientesActionPerformed

    private void visualizarNuevoTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarNuevoTiempoActionPerformed
        VisualizarTiempos eleccion = new VisualizarTiempos(nombreTienda, codigoTienda);
        eleccion.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_visualizarNuevoTiempoActionPerformed

    /**
     */
    public void cargarFondo(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(Fondo.getWidth(), Fondo.getHeight(), Image.SCALE_DEFAULT));
        Fondo.setIcon(imageIconFinal);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Fondo;
    public javax.swing.JLabel Titulo;
    public javax.swing.JButton cerrarSesion;
    private javax.swing.JLabel infoTienda;
    public javax.swing.JButton inicio;
    public javax.swing.JButton irMenuEmpleado;
    public javax.swing.JButton visualizarClientes;
    public javax.swing.JButton visualizarEmpleado;
    public javax.swing.JButton visualizarNuevoTiempo;
    public javax.swing.JButton visualizarProductos;
    public javax.swing.JButton visualizarTiendas;
    // End of variables declaration//GEN-END:variables
}
