/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI.paraEmpleados;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author erikssonherlo
 */
public class MenuReportes extends javax.swing.JFrame {
    String Fondo1 = "FondoNaranja5.png";
    String Logotipo = "LogoHorizontalpequeño.png";
    protected String nombreTienda;
    protected String codigoTienda;
    /**
     * Creates new form Interfaz
     */
    public MenuReportes(String nombreTienda, String codigoTienda) {
        this.nombreTienda = nombreTienda;
        this.codigoTienda = codigoTienda;
        
        initComponents();
        infoTienda.setText(nombreTienda);
        cargarFondo(Fondo1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        inicio = new javax.swing.JButton();
        irReporte1 = new javax.swing.JButton();
        irReporte2 = new javax.swing.JButton();
        irReporte4 = new javax.swing.JButton();
        irReporte6 = new javax.swing.JButton();
        irMenuEmpleado = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        infoTienda = new javax.swing.JLabel();
        irReporte3 = new javax.swing.JButton();
        irReporte5 = new javax.swing.JButton();
        irReporte7 = new javax.swing.JButton();
        irReporte9 = new javax.swing.JButton();
        irReporte8 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(1, 1, 1));
        Titulo.setText("REPORTES");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 100, 210, 53));

        inicio.setBackground(new java.awt.Color(43, 46, 46));
        inicio.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        inicio.setForeground(new java.awt.Color(250, 250, 244));
        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoHorizontalpequeño.png"))); // NOI18N
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 222, 91));

        irReporte1.setBackground(new java.awt.Color(43, 46, 46));
        irReporte1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irReporte1.setForeground(new java.awt.Color(250, 250, 244));
        irReporte1.setText("Pedidos que llegaran a la Tienda");
        irReporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irReporte1ActionPerformed(evt);
            }
        });
        getContentPane().add(irReporte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 300, 40));

        irReporte2.setBackground(new java.awt.Color(43, 46, 46));
        irReporte2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irReporte2.setForeground(new java.awt.Color(250, 250, 244));
        irReporte2.setText("Pedidos pendientes de Verificación");
        irReporte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irReporte2ActionPerformed(evt);
            }
        });
        getContentPane().add(irReporte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 300, 40));

        irReporte4.setBackground(new java.awt.Color(43, 46, 46));
        irReporte4.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irReporte4.setForeground(new java.awt.Color(250, 250, 244));
        irReporte4.setText("Pedidos en Transito");
        irReporte4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irReporte4ActionPerformed(evt);
            }
        });
        getContentPane().add(irReporte4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 300, 40));

        irReporte6.setBackground(new java.awt.Color(43, 46, 46));
        irReporte6.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irReporte6.setForeground(new java.awt.Color(250, 250, 244));
        irReporte6.setText("Pedidos en Curso de un Cliente");
        irReporte6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irReporte6ActionPerformed(evt);
            }
        });
        getContentPane().add(irReporte6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 300, 40));

        irMenuEmpleado.setBackground(new java.awt.Color(43, 46, 46));
        irMenuEmpleado.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irMenuEmpleado.setForeground(new java.awt.Color(250, 250, 244));
        irMenuEmpleado.setText("Regresar Al Menú Anterior");
        irMenuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irMenuEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(irMenuEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 290, 40));

        cerrarSesion.setBackground(new java.awt.Color(43, 46, 46));
        cerrarSesion.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        cerrarSesion.setForeground(new java.awt.Color(250, 250, 244));
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 290, 40));

        infoTienda.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 14)); // NOI18N
        infoTienda.setText("Nombre Tienda");
        getContentPane().add(infoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 102, -1, 20));

        irReporte3.setBackground(new java.awt.Color(43, 46, 46));
        irReporte3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irReporte3.setForeground(new java.awt.Color(250, 250, 244));
        irReporte3.setText("Pedidos Atrasados");
        irReporte3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irReporte3ActionPerformed(evt);
            }
        });
        getContentPane().add(irReporte3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 300, 40));

        irReporte5.setBackground(new java.awt.Color(43, 46, 46));
        irReporte5.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irReporte5.setForeground(new java.awt.Color(250, 250, 244));
        irReporte5.setText("Compras realizadas por un Cliente");
        irReporte5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irReporte5ActionPerformed(evt);
            }
        });
        getContentPane().add(irReporte5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 300, 40));

        irReporte7.setBackground(new java.awt.Color(43, 46, 46));
        irReporte7.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irReporte7.setForeground(new java.awt.Color(250, 250, 244));
        irReporte7.setText("Productos más vendidos al Tiempo");
        irReporte7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irReporte7ActionPerformed(evt);
            }
        });
        getContentPane().add(irReporte7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 300, 40));

        irReporte9.setBackground(new java.awt.Color(43, 46, 46));
        irReporte9.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irReporte9.setForeground(new java.awt.Color(250, 250, 244));
        irReporte9.setText("Productos sin Ventas");
        irReporte9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irReporte9ActionPerformed(evt);
            }
        });
        getContentPane().add(irReporte9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 300, 40));

        irReporte8.setBackground(new java.awt.Color(43, 46, 46));
        irReporte8.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irReporte8.setForeground(new java.awt.Color(250, 250, 244));
        irReporte8.setText("Productos más vendidos en Tienda");
        irReporte8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irReporte8ActionPerformed(evt);
            }
        });
        getContentPane().add(irReporte8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 300, 40));

        Fondo.setBackground(new java.awt.Color(59, 55, 51));
        Fondo.setText("Fondo General");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
            ElegirTienda eleccion = new ElegirTienda();
            eleccion.setVisible(true);
            this.setVisible(false);              // TODO add your handling code here:
              
              
    }//GEN-LAST:event_inicioActionPerformed

    private void irMenuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irMenuEmpleadoActionPerformed
            MenuEmpleado eleccion = new MenuEmpleado(nombreTienda,codigoTienda);
              eleccion.setVisible(true);
              this.setVisible(false);
    }//GEN-LAST:event_irMenuEmpleadoActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
    Inicio iniciarInterfaz = new Inicio();
        iniciarInterfaz.setVisible(true);   
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void irReporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irReporte1ActionPerformed
        Reporte1 eleccion = new Reporte1(nombreTienda, codigoTienda);
        eleccion.setVisible(true);
              this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_irReporte1ActionPerformed

    private void irReporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irReporte2ActionPerformed
       VisualizarProductos eleccion = new VisualizarProductos(nombreTienda, codigoTienda);
       eleccion.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_irReporte2ActionPerformed

    private void irReporte4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irReporte4ActionPerformed
        MenuNuevoEmpleado eleccion = new MenuNuevoEmpleado(nombreTienda, codigoTienda);
        eleccion.setVisible(true);
        this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_irReporte4ActionPerformed

    private void irReporte6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irReporte6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irReporte6ActionPerformed

    private void irReporte3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irReporte3ActionPerformed
        VisualizarTiempos eleccion = new VisualizarTiempos(nombreTienda, codigoTienda);
        eleccion.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_irReporte3ActionPerformed

    private void irReporte5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irReporte5ActionPerformed
        Reporte5 eleccion = new Reporte5(nombreTienda, codigoTienda);
        eleccion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_irReporte5ActionPerformed

    private void irReporte7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irReporte7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irReporte7ActionPerformed

    private void irReporte9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irReporte9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irReporte9ActionPerformed

    private void irReporte8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irReporte8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irReporte8ActionPerformed

    /**
     */
    public void cargarFondo(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(Fondo.getWidth(), Fondo.getHeight(), Image.SCALE_DEFAULT));
        Fondo.setIcon(imageIconFinal);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Fondo;
    public javax.swing.JLabel Titulo;
    public javax.swing.JButton cerrarSesion;
    private javax.swing.JLabel infoTienda;
    public javax.swing.JButton inicio;
    public javax.swing.JButton irMenuEmpleado;
    public javax.swing.JButton irReporte1;
    public javax.swing.JButton irReporte2;
    public javax.swing.JButton irReporte3;
    public javax.swing.JButton irReporte4;
    public javax.swing.JButton irReporte5;
    public javax.swing.JButton irReporte6;
    public javax.swing.JButton irReporte7;
    public javax.swing.JButton irReporte8;
    public javax.swing.JButton irReporte9;
    // End of variables declaration//GEN-END:variables
}
