/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI.paraEmpleados;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author erikssonherlo
 */
public class model extends javax.swing.JFrame {
    String Fondo1 = "FondoNaranja5.png";
    String Logotipo = "LogoHorizontalpequeño.png";
    /**
     * Creates new form Interfaz
     */
    public model() {
        initComponents();
        cargarFondo(Fondo1);
        cargarLogotipo(Logotipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        IngresoUsuario = new javax.swing.JLabel();
        IngresoContraseña = new javax.swing.JLabel();
        Ingresar = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        Salir1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setText("Logo");
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 222, 91));

        Titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(1, 1, 1));
        Titulo.setText("TIENDAS");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 230, 53));

        IngresoUsuario.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        IngresoUsuario.setForeground(new java.awt.Color(4, 2, 2));
        IngresoUsuario.setText("Ingrese el Usuario:");
        getContentPane().add(IngresoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 250, 30));

        IngresoContraseña.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        IngresoContraseña.setForeground(new java.awt.Color(4, 2, 2));
        IngresoContraseña.setText("Ingrese su Contraseña:");
        getContentPane().add(IngresoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 230, 30));

        Ingresar.setBackground(new java.awt.Color(43, 46, 46));
        Ingresar.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(250, 250, 244));
        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        getContentPane().add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 445, 290, 40));

        inicio.setBackground(new java.awt.Color(43, 46, 46));
        inicio.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        inicio.setForeground(new java.awt.Color(250, 250, 244));
        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoHorizontalpequeño.png"))); // NOI18N
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 222, 91));

        Salir1.setBackground(new java.awt.Color(43, 46, 46));
        Salir1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        Salir1.setForeground(new java.awt.Color(250, 250, 244));
        Salir1.setText("Salir");
        Salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir1ActionPerformed(evt);
            }
        });
        getContentPane().add(Salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 290, 40));

        Fondo.setBackground(new java.awt.Color(59, 55, 51));
        Fondo.setText("Fondo General");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
              // TODO add your handling code here:
              model eleccion = new model();
              eleccion.setVisible(true);
              this.setVisible(false);
              
    }//GEN-LAST:event_inicioActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed

    }//GEN-LAST:event_IngresarActionPerformed

    private void Salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir1ActionPerformed
    System.exit(0);          // TODO add your handling code here:
    }//GEN-LAST:event_Salir1ActionPerformed

    /**
     */
    public void cargarFondo(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(Fondo.getWidth(), Fondo.getHeight(), Image.SCALE_DEFAULT));
        Fondo.setIcon(imageIconFinal);
    }
        public void cargarLogotipo(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(Logo.getWidth(), Logo.getHeight(), Image.SCALE_DEFAULT));
        Logo.setIcon(imageIconFinal);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Fondo;
    public javax.swing.JButton Ingresar;
    public javax.swing.JLabel IngresoContraseña;
    public javax.swing.JLabel IngresoUsuario;
    public javax.swing.JLabel Logo;
    public javax.swing.JButton Salir1;
    public javax.swing.JLabel Titulo;
    public javax.swing.JButton inicio;
    // End of variables declaration//GEN-END:variables
}
