/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI.paraEmpleados;

import accesoAObjetos.AccesoProducto;
import accesoAObjetos.AccesoTiempo;
import accesoAObjetos.AccesoTienda;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import objetos.Producto;
import objetos.Tiempo;
import objetos.Tienda;

/**
 *
 * @author erikssonherlo
 */
public class NuevoTiempo extends javax.swing.JFrame {
    String Fondo1 = "FondoNaranja5.png";
    String Logotipo = "LogoHorizontalpequeño.png";
    protected String nombreTienda;
    protected String codigoTienda;
    /**
     * Creates new form Interfaz
     */
    public NuevoTiempo(String nombreTienda, String codigoTienda) {
        this.nombreTienda = nombreTienda;
        this.codigoTienda = codigoTienda;
        
        initComponents();
        cargarFondo(Fondo1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        irMenuNuevaInfo = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        inUsuario2 = new javax.swing.JLabel();
        inUsuario1 = new javax.swing.JLabel();
        inUsuario3 = new javax.swing.JLabel();
        textoUsuario1 = new javax.swing.JTextField();
        textoUsuario2 = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        inUsuario8 = new javax.swing.JLabel();
        inUsuario9 = new javax.swing.JLabel();
        inUsuario10 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(1, 1, 1));
        Titulo.setText("NUEVO TIEMPO");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 400, 53));

        irMenuNuevaInfo.setBackground(new java.awt.Color(43, 46, 46));
        irMenuNuevaInfo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irMenuNuevaInfo.setForeground(new java.awt.Color(250, 250, 244));
        irMenuNuevaInfo.setText("Regresar");
        irMenuNuevaInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irMenuNuevaInfoActionPerformed(evt);
            }
        });
        getContentPane().add(irMenuNuevaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 480, 150, 40));

        inicio.setBackground(new java.awt.Color(43, 46, 46));
        inicio.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        inicio.setForeground(new java.awt.Color(250, 250, 244));
        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoHorizontalpequeño.png"))); // NOI18N
        inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicioMouseEntered(evt);
            }
        });
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 222, 66));

        cerrarSesion.setBackground(new java.awt.Color(43, 46, 46));
        cerrarSesion.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        cerrarSesion.setForeground(new java.awt.Color(250, 250, 244));
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 150, 40));

        inUsuario2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        inUsuario2.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario2.setText("Ingrese el Código Destino:*");
        getContentPane().add(inUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 250, 30));

        inUsuario1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 12)); // NOI18N
        inUsuario1.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario1.setText("IMPORTANTE: Para poder crear un Nuevo Tiempo debe haber creado una Nueva Tienda ");
        getContentPane().add(inUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 155, 550, 30));

        inUsuario3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        inUsuario3.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario3.setText("Ingrese el Tiempo:         +*");
        getContentPane().add(inUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 250, 30));

        textoUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(textoUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 290, 30));

        textoUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario2ActionPerformed(evt);
            }
        });
        textoUsuario2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoUsuario2KeyTyped(evt);
            }
        });
        getContentPane().add(textoUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 290, 30));

        agregar.setBackground(new java.awt.Color(43, 46, 46));
        agregar.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        agregar.setForeground(new java.awt.Color(250, 250, 244));
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 150, 40));

        inUsuario8.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 10)); // NOI18N
        inUsuario8.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario8.setText("* CAMPOS OBLIGATORIOS");
        getContentPane().add(inUsuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 522, 160, 20));

        inUsuario9.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 10)); // NOI18N
        inUsuario9.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario9.setText("+EN DIAS");
        getContentPane().add(inUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 522, 160, 20));

        inUsuario10.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 12)); // NOI18N
        inUsuario10.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario10.setText("con Anterioridad y haber ingresado en dicha Tienda.");
        getContentPane().add(inUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 175, 540, 30));

        Fondo.setBackground(new java.awt.Color(59, 55, 51));
        Fondo.setText("Fondo General");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
              // TODO add your handling code here:
             ElegirTienda eleccion = new ElegirTienda();
            eleccion.setVisible(true);
            this.setVisible(false); 
              
    }//GEN-LAST:event_inicioActionPerformed

    private void irMenuNuevaInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irMenuNuevaInfoActionPerformed
            MenuNuevoProducto eleccion = new MenuNuevoProducto(nombreTienda, codigoTienda);
              eleccion.setVisible(true);
              this.setVisible(false);
    }//GEN-LAST:event_irMenuNuevaInfoActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        Inicio iniciarInterfaz = new Inicio();
        iniciarInterfaz.setVisible(true);    
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void textoUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario1ActionPerformed

    private void textoUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario2ActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        
        String tiendaDestino =textoUsuario1.getText();
        int tiempo = Integer.parseInt(textoUsuario2.getText());
        if (tiendaDestino.equals("") || tiempo==0){
            JOptionPane.showMessageDialog(null, "Ingrese todos los Campos Obligatorios");
        }else{
            Tiempo nuevo = new Tiempo(codigoTienda, tiendaDestino, tiempo);
            accesoAObjetos.AccesoTiempo llenar = new AccesoTiempo();
            
             if(!llenar.insertarTiempo(nuevo))
        {   JOptionPane.showMessageDialog(null, "No se puedo Ingresar un Nuevo Tiempo en la Tienda con el Codigo: "+codigoTienda+"\ndebido a que tiene datos repetidos con otra Tiempo ingresada en la Base de Datos");
        }else{
            JOptionPane.showMessageDialog(null, "Tiempo entre Tiendas Agregado Exitosamente");
            MenuEmpleado eleccion = new MenuEmpleado(nombreTienda,codigoTienda);
              eleccion.setVisible(true);
              this.setVisible(false);
              this.dispose();
        }
        }
        
    }//GEN-LAST:event_agregarActionPerformed

    private void textoUsuario2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUsuario2KeyTyped
    char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario2KeyTyped

    private void inicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseEntered
        
    }//GEN-LAST:event_inicioMouseEntered

    /**
     */
    public void cargarFondo(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(Fondo.getWidth(), Fondo.getHeight(), Image.SCALE_DEFAULT));
        Fondo.setIcon(imageIconFinal);
    }
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Fondo;
    public javax.swing.JLabel Titulo;
    public javax.swing.JButton agregar;
    public javax.swing.JButton cerrarSesion;
    public javax.swing.JLabel inUsuario1;
    public javax.swing.JLabel inUsuario10;
    public javax.swing.JLabel inUsuario2;
    public javax.swing.JLabel inUsuario3;
    public javax.swing.JLabel inUsuario8;
    public javax.swing.JLabel inUsuario9;
    public javax.swing.JButton inicio;
    public javax.swing.JButton irMenuNuevaInfo;
    public javax.swing.JTextField textoUsuario1;
    public javax.swing.JTextField textoUsuario2;
    // End of variables declaration//GEN-END:variables
}
