/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI.paraEmpleados;

import accesoAObjetos.AccesoCliente;
import accesoAObjetos.AccesoPedido;
import accesoAObjetos.AccesoProducto;
import accesoAObjetos.AccesoTienda;
import conexionMySQL.Conexion;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Cliente;
import objetos.Pedido;
import objetos.Producto;
import objetos.Tienda;

/**
 *
 * @author erikssonherlo
 */
public class NuevoPedido extends javax.swing.JFrame {
    String Fondo1 = "FondoNaranja5.png";
    String Logotipo = "LogoHorizontalpequeño.png";
    protected String nombreTienda;
    protected String codigoTienda;
    protected ArrayList<Pedido> listaProductosPedido= new ArrayList<>();    //AQUI SE GUARDAN TODOS LOS DATOS DEL DETALLE PEDIDO
    int registros=0;
    protected ArrayList<String> tablaProductosTiendaOrigen= new ArrayList<>();
    protected ArrayList<Double> creditoDisponibleCliente = new ArrayList<>();
    protected ArrayList<String> listaNITCliente = new ArrayList<>();
    private int codigoPedido,existenciaDelProducto,seleccion;
    String infoAuxCredito ;
    String tiendaOrigen,fechaPedido;
    String infoTotal,infoCodigoPedido,infoTotalAPagar,infoAnticipoTotal;
     Double total = 0.0,subTotal=0.0;
     Double totalAPagar = 0.0;
    Double auxTotal = 0.0;
    Double auxCredito = 0.0, auxAnticipo=0.0;
    String codigoProducto;
    String auxFechaLlegada;
      
    int cantidad;
    Double precio,caja=0.0;
        Double anticipoTotal=0.0;
        Double anticipoEfectivo=0.0,anticipoCredito=0.0;
    DefaultTableModel model = new DefaultTableModel();
     /**
     * Creates new form Interfaz
     */
    public NuevoPedido(String nombreTienda, String codigoTienda) throws SQLException {
        this.nombreTienda = nombreTienda;
        this.codigoTienda = codigoTienda;
        
        initComponents();
        infoTienda.setText(this.nombreTienda);
        listaProductosPedido.isEmpty();
        //mostrarTabla();
        llenarCombos();
        obtenerCodigoPedido();
        infTotalPedido.setVisible(false);
        infTotalAnticipo.setVisible(false);
        infTotalAPagar.setVisible(false);
        infCodigoPedido.setVisible(false);
        infCreditoDisponible.setVisible(false);
        agregar.setVisible(false);
        model.setColumnIdentifiers(new Object[]{"Codigo Pedido", "Tienda Origen", "Tienda Destino", "Codigo Producto","Cantidad","Precio","SubTotal"});
        this.tableProductosDelPedido.setModel(model);
        cargarFondo(Fondo1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        irMenuEmpleado = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        infUsuario3 = new javax.swing.JLabel();
        inUsuario13 = new javax.swing.JLabel();
        textoUsuario1 = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        inUsuario8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        inUsuario10 = new javax.swing.JLabel();
        inUsuario11 = new javax.swing.JLabel();
        comboTienda = new javax.swing.JComboBox<>();
        buscarTienda = new javax.swing.JButton();
        inUsuario12 = new javax.swing.JLabel();
        infoTienda = new javax.swing.JLabel();
        comboNITCliente = new javax.swing.JComboBox<>();
        infUsuario2 = new javax.swing.JLabel();
        infUsuario1 = new javax.swing.JLabel();
        infCodigoPedido = new javax.swing.JLabel();
        infUsuario4 = new javax.swing.JLabel();
        infUsuario5 = new javax.swing.JLabel();
        infUsuario6 = new javax.swing.JLabel();
        infUsuario7 = new javax.swing.JLabel();
        infTotalPedido = new javax.swing.JLabel();
        infTotalAnticipo = new javax.swing.JLabel();
        textoUsuario2 = new javax.swing.JTextField();
        textoUsuario3 = new javax.swing.JTextField();
        inUsuario14 = new javax.swing.JLabel();
        infTotalAPagar = new javax.swing.JLabel();
        infUsuario12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProductosDelPedido = new javax.swing.JTable();
        infUsuario11 = new javax.swing.JLabel();
        infUsuario13 = new javax.swing.JLabel();
        infUsuario14 = new javax.swing.JLabel();
        textoUsuario5 = new javax.swing.JTextField();
        textoUsuario6 = new javax.swing.JTextField();
        textoUsuario7 = new javax.swing.JTextField();
        agregarProducto = new javax.swing.JButton();
        inUsuario9 = new javax.swing.JLabel();
        infUsuario15 = new javax.swing.JLabel();
        infCreditoDisponible = new javax.swing.JLabel();
        agregarDatosPedido = new javax.swing.JButton();
        verCredito = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(1, 1, 1));
        Titulo.setText("NUEVO PEDIDO");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 20, 400, 53));

        irMenuEmpleado.setBackground(new java.awt.Color(43, 46, 46));
        irMenuEmpleado.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irMenuEmpleado.setForeground(new java.awt.Color(250, 250, 244));
        irMenuEmpleado.setText("Regresar");
        irMenuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irMenuEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(irMenuEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 150, 40));

        inicio.setBackground(new java.awt.Color(43, 46, 46));
        inicio.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        inicio.setForeground(new java.awt.Color(250, 250, 244));
        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoHorizontalpequeño.png"))); // NOI18N
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 222, 66));

        cerrarSesion.setBackground(new java.awt.Color(43, 46, 46));
        cerrarSesion.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        cerrarSesion.setForeground(new java.awt.Color(250, 250, 244));
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, 150, 40));

        infUsuario3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario3.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario3.setText("Código del Pedido:");
        getContentPane().add(infUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 160, 30));

        inUsuario13.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 10)); // NOI18N
        inUsuario13.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario13.setText("AAAA-MM-DD");
        getContentPane().add(inUsuario13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 80, 20));

        textoUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario1ActionPerformed(evt);
            }
        });
        textoUsuario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoUsuario1KeyTyped(evt);
            }
        });
        getContentPane().add(textoUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 130, 30));

        agregar.setBackground(new java.awt.Color(43, 46, 46));
        agregar.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        agregar.setForeground(new java.awt.Color(250, 250, 244));
        agregar.setText("Agregar Pedido");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 150, 40));

        inUsuario8.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 10)); // NOI18N
        inUsuario8.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario8.setText("**TODOS LOS CAMPOS SON OBLIGATORIOS");
        getContentPane().add(inUsuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 250, 20));

        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Fabricante", "Codigo del Producto", "Existencia", "Precio", "TIenda de Origen", "Descripción", "Garantia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 750, 130));

        inUsuario10.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        inUsuario10.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario10.setText("PRODUCTOS");
        getContentPane().add(inUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 80, 120, 30));

        inUsuario11.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        inUsuario11.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario11.setText("Buscar por: ");
        getContentPane().add(inUsuario11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 105, 130, 30));

        comboTienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tienda" }));
        comboTienda.setToolTipText("");
        comboTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTiendaActionPerformed(evt);
            }
        });
        getContentPane().add(comboTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 155, 150, 30));

        buscarTienda.setBackground(new java.awt.Color(43, 46, 46));
        buscarTienda.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        buscarTienda.setForeground(new java.awt.Color(250, 250, 244));
        buscarTienda.setText("Buscar");
        buscarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTiendaActionPerformed(evt);
            }
        });
        getContentPane().add(buscarTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 150, 30));

        inUsuario12.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        inUsuario12.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario12.setText("INFORMACIÓN DE LOS PRODUCTOS: **");
        getContentPane().add(inUsuario12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 390, 30));

        infoTienda.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 14)); // NOI18N
        infoTienda.setText("Nombre Tienda");
        getContentPane().add(infoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        comboNITCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIT" }));
        comboNITCliente.setToolTipText("");
        comboNITCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNITClienteActionPerformed(evt);
            }
        });
        getContentPane().add(comboNITCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 80, 30));

        infUsuario2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario2.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario2.setText("Ingrese la Fecha de Hoy:*");
        getContentPane().add(infUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 210, 30));

        infUsuario1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario1.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario1.setText("Ingrese el NIT del Cliente:");
        getContentPane().add(infUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 230, 30));

        infCodigoPedido.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infCodigoPedido.setForeground(new java.awt.Color(4, 2, 2));
        infCodigoPedido.setText("No.");
        getContentPane().add(infCodigoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 60, 30));

        infUsuario4.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario4.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario4.setText("Anticipo Efectivo:");
        getContentPane().add(infUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 150, 30));

        infUsuario5.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario5.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario5.setText("Anticipo Credito:");
        getContentPane().add(infUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 150, 30));

        infUsuario6.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario6.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario6.setText("Anticipo Total:");
        getContentPane().add(infUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 130, 30));

        infUsuario7.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario7.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario7.setText("Total del Pedido:");
        getContentPane().add(infUsuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 140, 30));

        infTotalPedido.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infTotalPedido.setForeground(new java.awt.Color(4, 2, 2));
        infTotalPedido.setText("000.00");
        getContentPane().add(infTotalPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 80, 30));

        infTotalAnticipo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infTotalAnticipo.setForeground(new java.awt.Color(4, 2, 2));
        infTotalAnticipo.setText("000.00");
        getContentPane().add(infTotalAnticipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 90, 30));

        textoUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario2ActionPerformed(evt);
            }
        });
        textoUsuario2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoUsuario2KeyTyped(evt);
            }
        });
        getContentPane().add(textoUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 80, 30));

        textoUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario3ActionPerformed(evt);
            }
        });
        textoUsuario3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoUsuario3KeyTyped(evt);
            }
        });
        getContentPane().add(textoUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 80, 30));

        inUsuario14.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        inUsuario14.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario14.setText("INFORMACIÓN DEL PEDIDO: **");
        getContentPane().add(inUsuario14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 360, 30));

        infTotalAPagar.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infTotalAPagar.setForeground(new java.awt.Color(4, 2, 2));
        infTotalAPagar.setText("000.00");
        getContentPane().add(infTotalAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 80, 30));

        infUsuario12.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario12.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario12.setText("Total a Pagar:");
        getContentPane().add(infUsuario12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 130, 30));

        tableProductosDelPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Pedido", "Tienda Origen", "Tienda Destino", "Codigo del Producto", "Cantidad", "Precio", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableProductosDelPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductosDelPedidoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableProductosDelPedido);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 750, 120));

        infUsuario11.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario11.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario11.setText("Cantidad:");
        getContentPane().add(infUsuario11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 80, 30));

        infUsuario13.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario13.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario13.setText("Código del Producto:");
        getContentPane().add(infUsuario13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, 30));

        infUsuario14.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario14.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario14.setText("Precio:");
        getContentPane().add(infUsuario14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 70, 30));

        textoUsuario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario5ActionPerformed(evt);
            }
        });
        textoUsuario5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoUsuario5KeyTyped(evt);
            }
        });
        getContentPane().add(textoUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 110, 30));

        textoUsuario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario6ActionPerformed(evt);
            }
        });
        textoUsuario6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoUsuario6KeyTyped(evt);
            }
        });
        getContentPane().add(textoUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 80, 30));

        textoUsuario7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuario7ActionPerformed(evt);
            }
        });
        textoUsuario7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoUsuario7KeyTyped(evt);
            }
        });
        getContentPane().add(textoUsuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 80, 30));

        agregarProducto.setBackground(new java.awt.Color(43, 46, 46));
        agregarProducto.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        agregarProducto.setForeground(new java.awt.Color(250, 250, 244));
        agregarProducto.setText("Agregar Producto");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(agregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 170, 40));

        inUsuario9.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 10)); // NOI18N
        inUsuario9.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario9.setText("*FECHA EN FORMATO AÑO-MES-DIA");
        getContentPane().add(inUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 650, 250, 20));

        infUsuario15.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infUsuario15.setForeground(new java.awt.Color(4, 2, 2));
        infUsuario15.setText("Credito Disponible:");
        getContentPane().add(infUsuario15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 170, 30));

        infCreditoDisponible.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 16)); // NOI18N
        infCreditoDisponible.setForeground(new java.awt.Color(4, 2, 2));
        infCreditoDisponible.setText("000.00");
        getContentPane().add(infCreditoDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 80, 30));

        agregarDatosPedido.setBackground(new java.awt.Color(43, 46, 46));
        agregarDatosPedido.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        agregarDatosPedido.setForeground(new java.awt.Color(250, 250, 244));
        agregarDatosPedido.setText("Agregar Datos");
        agregarDatosPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDatosPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(agregarDatosPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 170, 40));

        verCredito.setBackground(new java.awt.Color(43, 46, 46));
        verCredito.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        verCredito.setForeground(new java.awt.Color(250, 250, 244));
        verCredito.setText("Ver Credito");
        verCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCreditoActionPerformed(evt);
            }
        });
        getContentPane().add(verCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 515, 170, 30));

        Fondo.setBackground(new java.awt.Color(59, 55, 51));
        Fondo.setText("Fondo General");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void mostrarTabla(String tiendaOrigen) {
        DefaultTableModel model = new DefaultTableModel();
        //Conexion conexion = new Conexion();
        ResultSet rs = Conexion.getTabla("SELECT * FROM EXISTENCIA_PRODUCTO WHERE Codigo_Tienda= '"+tiendaOrigen+"'");
        model.setColumnIdentifiers(new Object[]{"Nombre", "Fabricante", "Codigo Producto", "Existencia","Precio","Tienda Origen","Descripcion","Garantia"});
        
        try {
            while (rs.next()) {
               
                model.addRow(new Object[]{rs.getString("Nombre"), rs.getString("Fabricante"), rs.getString("Codigo_Producto"), rs.getInt("Existencia"),rs.getDouble("Precio"),rs.getString("Codigo_Tienda"),rs.getString("Descripcion"),rs.getInt("Garantia")});
            }
            tableProductos.setModel(model);
        } catch (SQLException e) {
        }
    }
    
 
    private void llenarCombos() throws SQLException {
        
        
        ResultSet rs = Conexion.getTabla("SELECT Nombre,Codigo_Tienda FROM TIENDA WHERE Codigo_Tienda <> '"+codigoTienda+"'");
            try {
            while (rs.next()) {
                comboTienda.addItem(rs.getString(1));
                tablaProductosTiendaOrigen.add(rs.getString(2));
                }

        } catch (SQLException e) {

        }
     
        ResultSet rs1 = Conexion.getTabla("SELECT NIT,Credito_Compra FROM CLIENTE");
            try {
            while (rs1.next()) {
                comboNITCliente.addItem(rs1.getString(1));
                listaNITCliente.add(rs1.getString(1));
                creditoDisponibleCliente.add(rs1.getDouble(2));
                }

        } catch (SQLException e) {

        }
       
    }
    private void obtenerCodigoPedido() throws SQLException{
     ResultSet rs2 = Conexion.getTabla("SELECT Codigo_Pedido FROM PEDIDO WHERE Codigo_Pedido = (SELECT MAX(Codigo_Pedido) FROM PEDIDO);");
            try {
            while (rs2.next()) {
                codigoPedido= rs2.getInt(1)+1;
                }

        } catch (SQLException e) {

        }
            
    }
  private void obtenerFechaLlegada(int codigoPedido) throws SQLException{
     ResultSet rs2 = Conexion.getTabla("SELECT Fecha_Llegada FROM PEDIDO WHERE Codigo_Pedido = "+codigoPedido);
            try {
            while (rs2.next()) {
                auxFechaLlegada = rs2.getString(1);
                }

        } catch (SQLException e) {

        }
            
    }
    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
              // TODO add your handling code here:
             ElegirTienda eleccion = new ElegirTienda();
            eleccion.setVisible(true);
            this.setVisible(false); 
              
    }//GEN-LAST:event_inicioActionPerformed

    private void irMenuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irMenuEmpleadoActionPerformed
            MenuEmpleado eleccion = new MenuEmpleado(nombreTienda, codigoTienda);
              eleccion.setVisible(true);
              this.setVisible(false);
    }//GEN-LAST:event_irMenuEmpleadoActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        Inicio iniciarInterfaz = new Inicio();
        iniciarInterfaz.setVisible(true);    
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void textoUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario1ActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        String estado = "Transito";
        AccesoPedido llenar = new AccesoPedido();
        AccesoProducto actualizar = new AccesoProducto();
        AccesoCliente cambiar = new AccesoCliente();
        for (int i=0;i<tableProductosDelPedido.getRowCount();i++){
            
           // llenar.insertarPedido(new Pedido(codigoPedido, tiendaOrigen, codigoTienda, fechaPedido,listaNITCliente.get(comboNITCliente.getSelectedIndex()-1), (String)tableProductosDelPedido.getValueAt(i,3),cantidad,subTotal,
            
              //Este es el constructor funcional      
            llenar.insertarNuevoPedido(new Pedido(codigoPedido, tiendaOrigen, codigoTienda, fechaPedido,listaNITCliente.get(comboNITCliente.getSelectedIndex()-1), (String)tableProductosDelPedido.getValueAt(i,3), (Integer)tableProductosDelPedido.getValueAt(i, 4),(Double)tableProductosDelPedido.getValueAt(i, 6), anticipoEfectivo,fechaPedido,auxTotal,anticipoCredito, anticipoTotal,totalAPagar,0,caja,estado,(Double)tableProductosDelPedido.getValueAt(i, 5)));
            actualizar.actualizarExistencias(new Producto((String)tableProductosDelPedido.getValueAt(i, 3),(Integer)tableProductosDelPedido.getValueAt(i, 4) , tiendaOrigen));
            System.out.println(i+"ra Fila -----------------------------------");
            System.out.println("Codigo del Pedido: "+codigoPedido);
            System.out.println("Tienda Origen: "+tiendaOrigen);
            System.out.println("Tienda Destino: "+codigoTienda);
            System.out.println("Fecha: "+fechaPedido);
            System.out.println("NIT Cliente: "+listaNITCliente.get(comboNITCliente.getSelectedIndex()-1));
            System.out.println("Codigo Producto: "+(String)tableProductosDelPedido.getValueAt(i, 3));
            System.out.println("Cantidad: "+(Integer)tableProductosDelPedido.getValueAt(i, 4));
            System.out.println("SubTotal: "+(Double)tableProductosDelPedido.getValueAt(i, 6));
            System.out.println("Anticipo Efectivo: "+anticipoEfectivo);
            System.out.println("Fecha Llegada: "+fechaPedido);
            System.out.println("Total Pedido: "+auxTotal);
            System.out.println("Anticipo Credito: "+anticipoCredito);
            System.out.println("Anticipo Total: "+anticipoTotal);
            System.out.println("Total A Pagar: "+totalAPagar);
            System.out.println("Pago Total: "+0);
            System.out.println("Caja: "+caja);
            System.out.println("Estado: "+estado);
            System.out.println("Precio: "+(Double)tableProductosDelPedido.getValueAt(i, 5));

        }
        cambiar.actualizarCredito(new Cliente(listaNITCliente.get(comboNITCliente.getSelectedIndex()-1), anticipoCredito));
            
        try {
            
            obtenerFechaLlegada(codigoPedido);


        } catch (SQLException ex) {
            Logger.getLogger(NuevoPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "El Pedido No. "+codigoPedido+" se ha procesado correctamente, \n su pedido estará llegando a la tienda el dia "+auxFechaLlegada);
        MenuEmpleado eleccion = new MenuEmpleado(nombreTienda, codigoTienda);
              eleccion.setVisible(true);
              this.setVisible(false);
    }//GEN-LAST:event_agregarActionPerformed

    private void tableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductosMouseClicked
        seleccion = tableProductos.getSelectedRow();
        textoUsuario5.setText(tableProductos.getValueAt(seleccion, 2).toString());
        textoUsuario7.setText(tableProductos.getValueAt(seleccion, 4).toString());
        existenciaDelProducto = (int) tableProductos.getValueAt(seleccion, 3);
        
    }//GEN-LAST:event_tableProductosMouseClicked

    private void comboTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTiendaActionPerformed

    private void buscarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTiendaActionPerformed
        if(comboTienda.getSelectedIndex()!=0){
           
            mostrarTabla(tablaProductosTiendaOrigen.get(comboTienda.getSelectedIndex()-1));
            
        
        } else
        {
            JOptionPane.showMessageDialog(null, "Por favor, Seleccione una Tienda");
                   
        }
    }//GEN-LAST:event_buscarTiendaActionPerformed

    private void comboNITClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNITClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNITClienteActionPerformed

    private void textoUsuario1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUsuario1KeyTyped
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='-'){
       evt.consume();
   } 
        if(evt.getKeyChar()=='-'&&textoUsuario1.getText().contains("--")){
      evt.consume();
       }
    }//GEN-LAST:event_textoUsuario1KeyTyped

    private void textoUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario2ActionPerformed

    private void textoUsuario2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUsuario2KeyTyped
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&textoUsuario2.getText().contains(".")){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario2KeyTyped

    private void textoUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario3ActionPerformed

    private void textoUsuario3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUsuario3KeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&textoUsuario3.getText().contains(".")){
            evt.consume();
        }   
    }//GEN-LAST:event_textoUsuario3KeyTyped

    private void tableProductosDelPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductosDelPedidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableProductosDelPedidoMouseClicked

    private void textoUsuario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario5ActionPerformed

    private void textoUsuario5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUsuario5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario5KeyTyped

    private void textoUsuario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario6ActionPerformed

    private void textoUsuario6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUsuario6KeyTyped
        // TODO add your handling code here:
         char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }   
    }//GEN-LAST:event_textoUsuario6KeyTyped

    private void textoUsuario7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuario7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario7ActionPerformed

    private void textoUsuario7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoUsuario7KeyTyped
if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&textoUsuario7.getText().contains(".")){
            evt.consume();
        }           // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuario7KeyTyped

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
      /**
       * Metodo para Agregar Productos a la Tabla
       */
        //DECLARACION DE VARIABLES A UTILIZAR
        total=0.0;
        
        codigoProducto = textoUsuario5.getText();
        cantidad = Integer.parseInt(textoUsuario6.getText());
        precio = Double.parseDouble(textoUsuario7.getText());
       

        subTotal =cantidad*precio;
       
        total =+subTotal;
        auxTotal =auxTotal+total;
        
        totalAPagar = auxTotal - anticipoTotal;
        //BLOQUE DE STRINGS PARA EL ARRAYLIST
         infoTotal = Double.toString(auxTotal);
         infoCodigoPedido = Integer.toString(codigoPedido);
         infoTotalAPagar = Double.toString(totalAPagar);
        
        
        
        //PRIMERA VALIDACIÓN: ELECCION DE LA TIENDA
        if(comboTienda.getSelectedIndex()!=0){
            tiendaOrigen = tablaProductosTiendaOrigen.get(comboTienda.getSelectedIndex()-1);
        
            //ACCIONES DE VISUALIZACIÓN DE INFORMACION
            infCodigoPedido.setText(infoCodigoPedido);
            infCodigoPedido.setVisible(true);
            comboTienda.setVisible(false);
            buscarTienda.setVisible(false);
            //SEGUNDA VALIDACION: INGRESO DE CAMPOS OBLIGATORIOS
            if(tiendaOrigen.equals("") || codigoProducto.equals("") || textoUsuario6.getText().equals("") || textoUsuario7.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Ingrese todos los Campos Obligatorios");
            }
            else
            {
                //TERCERA VALIDACION: EXISTENCIA DE PRODUCTOS ELEGIDOS
                if(cantidad > existenciaDelProducto){
                    JOptionPane.showMessageDialog(null, "Ingrese una Cantidad de Productos que si se encuentre en la Tienda");
                    textoUsuario6.setText("");
                } else {
                    existenciaDelProducto = existenciaDelProducto -cantidad;
                    tableProductos.setValueAt(existenciaDelProducto, seleccion, 3);
                    model.addRow(new Object[]{codigoPedido, tiendaOrigen, codigoTienda, codigoProducto,cantidad,precio,subTotal});
                    textoUsuario5.setText("");
                    textoUsuario6.setText("");
                    textoUsuario7.setText("");
                    infTotalPedido.setText(infoTotal);
                    infTotalPedido.setVisible(true);
                    
                    
                    infTotalAnticipo.setText(infoAnticipoTotal);
                    infTotalAnticipo.setVisible(true);
                    
                    infTotalAPagar.setText(infoTotalAPagar);
                    infTotalAPagar.setVisible(true);
                    
                }
            }
        
        
        }else{
        tiendaOrigen = "";
        JOptionPane.showMessageDialog(null, "Elija una Tienda para Consultar los Productos");
        }
        
      

                                        
    }//GEN-LAST:event_agregarProductoActionPerformed

    private void agregarDatosPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDatosPedidoActionPerformed
    auxCredito = creditoDisponibleCliente.get(comboNITCliente.getSelectedIndex()-1);    
    //VALIDACION DE VALORES PARA EL ANTICIPO     
        if(textoUsuario2.getText().equals("") && textoUsuario3.getText().equals("")){
            anticipoEfectivo =0.0;
            anticipoCredito = 0.0;
        } else if(textoUsuario2.getText().equals("") && !textoUsuario3.getText().equals("")){
            anticipoEfectivo = 0.0;
            anticipoCredito = Double.parseDouble(textoUsuario3.getText());
        }else if(!textoUsuario2.getText().equals("") && textoUsuario3.getText().equals("")){
           anticipoEfectivo = Double.parseDouble(textoUsuario2.getText());
           anticipoCredito = 0.0;
        }else {
            anticipoEfectivo = Double.parseDouble(textoUsuario2.getText());
            anticipoCredito = Double.parseDouble(textoUsuario3.getText());
        }
        if(auxCredito ==0){
        anticipoCredito = 0.0;
        
        }
        anticipoTotal = anticipoEfectivo +anticipoCredito;
        fechaPedido = textoUsuario1.getText();
        auxAnticipo = auxTotal*0.25;
        
        
        //VALIDACION PORCENTAJE DEL PEDIDO
        if(anticipoTotal<auxAnticipo && auxCredito==0){
            JOptionPane.showMessageDialog(null, "El valor del Anticipo Efectivo debe ser mayor a "+auxAnticipo);
            
        } else if(anticipoTotal<auxAnticipo){
            JOptionPane.showMessageDialog(null, "El valor del Anticipo debe ser mayor a "+auxAnticipo);
        }
        //PRIMERA VALIDACION DE CAMPOS LLENOS
        System.out.println(comboNITCliente.getSelectedIndex());
        System.out.println(fechaPedido);
        System.out.println(anticipoTotal + "Mayor que "+ auxAnticipo);
        if(comboNITCliente.getSelectedIndex()!=0 && !fechaPedido.equals("") && anticipoTotal>auxAnticipo)
        {
              totalAPagar = auxTotal-anticipoTotal;
              infoAnticipoTotal = Double.toString(anticipoTotal);
              infoTotalAPagar = Double.toString(totalAPagar);
              auxCredito = creditoDisponibleCliente.get(comboNITCliente.getSelectedIndex()-1);
              auxCredito = auxCredito-anticipoCredito;
              String infoAuxCredito = auxCredito.toString();
              infCreditoDisponible.setText(infoAuxCredito);
              caja = anticipoTotal;
              infTotalAnticipo.setText(infoAnticipoTotal);
              infTotalAPagar.setText(infoTotalAPagar);
              agregar.setVisible(true);
              JOptionPane.showMessageDialog(null, "Datos Informativos, agregados correctamente");
        } else
        {
            JOptionPane.showMessageDialog(null, "Por favor, Ingrese todos los Datos en los Campos Obligatorios");
                   
        } 
        

    }//GEN-LAST:event_agregarDatosPedidoActionPerformed

    private void verCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCreditoActionPerformed
        infCreditoDisponible.setVisible(true);
        if(comboNITCliente.getSelectedIndex()!=0){
              
              auxCredito = creditoDisponibleCliente.get(comboNITCliente.getSelectedIndex()-1);
              infoAuxCredito= auxCredito.toString();
              infCreditoDisponible.setText(infoAuxCredito);
              
              
        } else
        {
            JOptionPane.showMessageDialog(null, "Por favor, Seleccione un Cliente");
                   
        }
    }//GEN-LAST:event_verCreditoActionPerformed
    
    /**
     */

    /**
     *
     * @param NombreImagen
     */
    public void cargarFondo(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(Fondo.getWidth(), Fondo.getHeight(), Image.SCALE_DEFAULT));
        Fondo.setIcon(imageIconFinal);
    }
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Fondo;
    public javax.swing.JLabel Titulo;
    public javax.swing.JButton agregar;
    public javax.swing.JButton agregarDatosPedido;
    public javax.swing.JButton agregarProducto;
    public javax.swing.JButton buscarTienda;
    public javax.swing.JButton cerrarSesion;
    private javax.swing.JComboBox<String> comboNITCliente;
    private javax.swing.JComboBox<String> comboTienda;
    public javax.swing.JLabel inUsuario10;
    public javax.swing.JLabel inUsuario11;
    public javax.swing.JLabel inUsuario12;
    public javax.swing.JLabel inUsuario13;
    public javax.swing.JLabel inUsuario14;
    public javax.swing.JLabel inUsuario8;
    public javax.swing.JLabel inUsuario9;
    public javax.swing.JLabel infCodigoPedido;
    public javax.swing.JLabel infCreditoDisponible;
    public javax.swing.JLabel infTotalAPagar;
    public javax.swing.JLabel infTotalAnticipo;
    public javax.swing.JLabel infTotalPedido;
    public javax.swing.JLabel infUsuario1;
    public javax.swing.JLabel infUsuario11;
    public javax.swing.JLabel infUsuario12;
    public javax.swing.JLabel infUsuario13;
    public javax.swing.JLabel infUsuario14;
    public javax.swing.JLabel infUsuario15;
    public javax.swing.JLabel infUsuario2;
    public javax.swing.JLabel infUsuario3;
    public javax.swing.JLabel infUsuario4;
    public javax.swing.JLabel infUsuario5;
    public javax.swing.JLabel infUsuario6;
    public javax.swing.JLabel infUsuario7;
    private javax.swing.JLabel infoTienda;
    public javax.swing.JButton inicio;
    public javax.swing.JButton irMenuEmpleado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTable tableProductosDelPedido;
    public javax.swing.JTextField textoUsuario1;
    public javax.swing.JTextField textoUsuario2;
    public javax.swing.JTextField textoUsuario3;
    public javax.swing.JTextField textoUsuario5;
    public javax.swing.JTextField textoUsuario6;
    public javax.swing.JTextField textoUsuario7;
    public javax.swing.JButton verCredito;
    // End of variables declaration//GEN-END:variables
}
