/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI.paraEmpleados;

import accesoAObjetos.AccesoProducto;
import accesoAObjetos.AccesoTienda;
import conexionMySQL.Conexion;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Producto;
import objetos.Tienda;
import reportes.Reporte5HTML;

/**
 *
 * @author erikssonherlo
 */
public class Reporte5 extends javax.swing.JFrame {
    String Fondo1 = "FondoNaranja5.png";
    String Logotipo = "LogoHorizontalpequeño.png";
    protected String nombreTienda;
    protected String codigoTienda;
    protected ArrayList<String> listaNombreCliente= new ArrayList<>();    //AQUI SE GUARDAN TODOS LOS DATOS DEL DETALLE PEDIDO
    String nombreCliente;
        String NITDelCliente;
      
    
    
     /**
     * Creates new form Interfaz
     */
    public Reporte5(String nombreTienda, String codigoTienda) {
        this.nombreTienda = nombreTienda;
        this.codigoTienda = codigoTienda;
        
        initComponents();
        infoTienda.setText(this.nombreTienda);
        nitCliente.setVisible(false);
        
        llenarCombos();
        
         cargarFondo(Fondo1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        irMenuEmpleado = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDetalleVentas = new javax.swing.JTable();
        buscarTienda = new javax.swing.JButton();
        infoTienda = new javax.swing.JLabel();
        exportarReporte = new javax.swing.JButton();
        descripcionReporte = new javax.swing.JLabel();
        comboNITCliente = new javax.swing.JComboBox<>();
        inUsuario12 = new javax.swing.JLabel();
        nitCliente = new javax.swing.JLabel();
        inUsuario14 = new javax.swing.JLabel();
        inUsuario15 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(1, 1, 1));
        Titulo.setText("REPORTE");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 250, 53));

        irMenuEmpleado.setBackground(new java.awt.Color(43, 46, 46));
        irMenuEmpleado.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        irMenuEmpleado.setForeground(new java.awt.Color(250, 250, 244));
        irMenuEmpleado.setText("Regresar");
        irMenuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irMenuEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(irMenuEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 150, 40));

        inicio.setBackground(new java.awt.Color(43, 46, 46));
        inicio.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        inicio.setForeground(new java.awt.Color(250, 250, 244));
        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoHorizontalpequeño.png"))); // NOI18N
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 222, 66));

        cerrarSesion.setBackground(new java.awt.Color(43, 46, 46));
        cerrarSesion.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        cerrarSesion.setForeground(new java.awt.Color(250, 250, 244));
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 150, 40));

        tableDetalleVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Venta", "Tienda Existencia", "Codigo Producto", "Cantidad", "Precio", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableDetalleVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDetalleVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDetalleVentas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 750, 170));

        buscarTienda.setBackground(new java.awt.Color(43, 46, 46));
        buscarTienda.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        buscarTienda.setForeground(new java.awt.Color(250, 250, 244));
        buscarTienda.setText("Buscar");
        buscarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTiendaActionPerformed(evt);
            }
        });
        getContentPane().add(buscarTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 150, 30));

        infoTienda.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 14)); // NOI18N
        infoTienda.setText("Nombre Tienda");
        getContentPane().add(infoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        exportarReporte.setBackground(new java.awt.Color(43, 46, 46));
        exportarReporte.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        exportarReporte.setForeground(new java.awt.Color(250, 250, 244));
        exportarReporte.setText("Exportar Reporte");
        exportarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(exportarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 230, 40));

        descripcionReporte.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        descripcionReporte.setForeground(new java.awt.Color(4, 2, 2));
        descripcionReporte.setText("Compras Realizadas por un Cliente");
        getContentPane().add(descripcionReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 75, 330, 30));

        comboNITCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIT" }));
        comboNITCliente.setToolTipText("");
        comboNITCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNITClienteActionPerformed(evt);
            }
        });
        getContentPane().add(comboNITCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 150, 30));

        inUsuario12.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        inUsuario12.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario12.setText("Buscar por: ");
        getContentPane().add(inUsuario12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 130, 30));

        nitCliente.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        nitCliente.setForeground(new java.awt.Color(4, 2, 2));
        nitCliente.setText("NIT Cliente");
        getContentPane().add(nitCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 130, 30));

        inUsuario14.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        inUsuario14.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario14.setText("Informacion");
        getContentPane().add(inUsuario14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        inUsuario15.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        inUsuario15.setForeground(new java.awt.Color(4, 2, 2));
        inUsuario15.setText("NIT:");
        getContentPane().add(inUsuario15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 60, 30));

        Fondo.setBackground(new java.awt.Color(59, 55, 51));
        Fondo.setText("Fondo General");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void mostrarTablaCompleta(String NITCliente) {
        //NITDelCliente = NITCliente;
        DefaultTableModel model = new DefaultTableModel();
        Conexion conexion = new Conexion();
        ResultSet rs = conexion.getTabla("SELECT dv.* FROM DETALLE_VENTAS dv INNER JOIN VENTAS v ON v.Id_Ventas = dv.Id_Ventas WHERE v.NIT_Cliente='"+NITCliente+"'");
        model.setColumnIdentifiers(new Object[]{"Id Ventas", "Tienda Existencia", "Codigo Producto", "Cantidad","Precio","SubTotal"});
        
        try {
            while (rs.next()) {               
                model.addRow(new Object[]{rs.getInt("Id_Ventas"), rs.getString("Tienda_Existencia"), rs.getString("Codigo_Producto"), rs.getInt("Cantidad_Venta"),rs.getDouble("Precio"),rs.getDouble("SubTotal")});
            }
            tableDetalleVentas.setModel(model);
        } catch (SQLException e) {
        }
    }
    

 
    private void llenarCombos() {
        
        Conexion conexion = new Conexion();
       ResultSet rs = conexion.getTabla("SELECT NIT FROM CLIENTE");
            try {
            while (rs.next()) {
                
                comboNITCliente.addItem(rs.getString(1));
                listaNombreCliente.add(rs.getString(1));
                
                
                }

        } catch (SQLException e) {

        }
       
    }
    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
              // TODO add your handling code here:
             ElegirTienda eleccion = new ElegirTienda();
            eleccion.setVisible(true);
            this.setVisible(false); 
              
    }//GEN-LAST:event_inicioActionPerformed

    private void irMenuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irMenuEmpleadoActionPerformed
            MenuEmpleado eleccion = new MenuEmpleado(nombreTienda, codigoTienda);
              eleccion.setVisible(true);
              this.setVisible(false);
    }//GEN-LAST:event_irMenuEmpleadoActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        Inicio iniciarInterfaz = new Inicio();
        iniciarInterfaz.setVisible(true);    
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void tableDetalleVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDetalleVentasMouseClicked
             
    }//GEN-LAST:event_tableDetalleVentasMouseClicked

    private void buscarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTiendaActionPerformed
        if(comboNITCliente.getSelectedIndex()!=0){
            //mostrarTablaCompleta(NITCliente);
            mostrarTablaCompleta(listaNombreCliente.get(comboNITCliente.getSelectedIndex()-1));
            nitCliente.setText(listaNombreCliente.get(comboNITCliente.getSelectedIndex()-1));
            nitCliente.setVisible(true);

        } else {
           JOptionPane.showMessageDialog(null, "Por favor, Seleccione un Campo de Busqueda");
        }
    }//GEN-LAST:event_buscarTiendaActionPerformed

    private void exportarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarReporteActionPerformed
        if(comboNITCliente.getSelectedIndex()!=0){    
            Reporte5HTML reporte = new Reporte5HTML();
            reporte.generarReporte(tableDetalleVentas, listaNombreCliente.get(comboNITCliente.getSelectedIndex()-1));
            JOptionPane.showMessageDialog(null, "Reporte Exportado con Exito");
        } else {
        JOptionPane.showMessageDialog(null, "Por favor, Seleccione un Campo de Busqueda para poder Generar el Reporte");
       
        }
    }//GEN-LAST:event_exportarReporteActionPerformed

    private void comboNITClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNITClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNITClienteActionPerformed

    /**
     */
    public void cargarFondo(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(Fondo.getWidth(), Fondo.getHeight(), Image.SCALE_DEFAULT));
        Fondo.setIcon(imageIconFinal);
    }
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Fondo;
    public javax.swing.JLabel Titulo;
    public javax.swing.JButton buscarTienda;
    public javax.swing.JButton cerrarSesion;
    private javax.swing.JComboBox<String> comboNITCliente;
    public javax.swing.JLabel descripcionReporte;
    public javax.swing.JButton exportarReporte;
    public javax.swing.JLabel inUsuario12;
    public javax.swing.JLabel inUsuario14;
    public javax.swing.JLabel inUsuario15;
    private javax.swing.JLabel infoTienda;
    public javax.swing.JButton inicio;
    public javax.swing.JButton irMenuEmpleado;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel nitCliente;
    private javax.swing.JTable tableDetalleVentas;
    // End of variables declaration//GEN-END:variables
}
