-- MySQL Script generated by MySQL Workbench
-- mié 19 ago 2020 03:41:11 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `Nombre` VARCHAR(45) NOT NULL,
  `NIT` VARCHAR(15) NOT NULL,
  `Telefono` VARCHAR(10) NOT NULL,
  `Credito_Compra` DOUBLE NOT NULL,
  `DPI` VARCHAR(20) NULL,
  `Correo_Electronico` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`NIT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIENDA` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Codigo_Tienda` VARCHAR(10) NOT NULL,
  `Telefono_1` VARCHAR(10) NOT NULL,
  `Telefono_2` VARCHAR(10) NULL,
  `Horario` VARCHAR(45) NULL,
  `Correo_Electronico` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_Tienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Codigo_Empleado` VARCHAR(10) NOT NULL,
  `Telefono` VARCHAR(10) NOT NULL,
  `DPI` VARCHAR(20) NOT NULL,
  `NIT` VARCHAR(15) NULL,
  `Correo_Electronico` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_Empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIEMPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIEMPO` (
  `Id_Tiempo` INT NOT NULL AUTO_INCREMENT,
  `Tienda_Origen` VARCHAR(10) NOT NULL,
  `Tienda_Destino` VARCHAR(10) NOT NULL,
  `Tiempo` INT NOT NULL,
  PRIMARY KEY (`Id_Tiempo`),
  INDEX `Tienda_Origen_idx` (`Tienda_Origen` ASC) VISIBLE,
  INDEX `Tienda_Destino_idx` (`Tienda_Destino` ASC) VISIBLE,
  CONSTRAINT `Tienda_Origen`
    FOREIGN KEY (`Tienda_Origen`)
    REFERENCES `mydb`.`TIENDA` (`Codigo_Tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tienda_Destino`
    FOREIGN KEY (`Tienda_Destino`)
    REFERENCES `mydb`.`TIENDA` (`Codigo_Tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO` (
  `Codigo_Pedido` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Fecha_Llegada` DATE NULL,
  `NIT_Cliente` VARCHAR(15) NOT NULL,
  `Anticipo_Efectivo` DOUBLE NULL,
  `Anticipo_Credito` DOUBLE NULL,
  `Total` DOUBLE NULL,
  `Anticipo` DOUBLE NULL,
  `Total_A_Pagar` DOUBLE NULL,
  `Pago_Total` DOUBLE NULL,
  `Caja` DOUBLE NULL,
  `Estado` VARCHAR(15) NULL,
  PRIMARY KEY (`Codigo_Pedido`),
  INDEX `fk_PEDIDO_CLIENTE1_idx` (`NIT_Cliente` ASC) VISIBLE,
  CONSTRAINT `NIT_Cliente`
    FOREIGN KEY (`NIT_Cliente`)
    REFERENCES `mydb`.`CLIENTE` (`NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENTAS` (
  `Id_Ventas` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `NIT_Cliente` VARCHAR(15) NOT NULL,
  `Total_A_Pagar` DOUBLE NULL,
  `Efectivo` DOUBLE NULL,
  `Credito_Cliente` DOUBLE NULL,
  `Caja` DOUBLE NULL,
  PRIMARY KEY (`Id_Ventas`),
  INDEX `fk_VENTAS_CLIENTE1_idx` (`NIT_Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_VENTAS_CLIENTE1`
    FOREIGN KEY (`NIT_Cliente`)
    REFERENCES `mydb`.`CLIENTE` (`NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EXISTENCIA_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EXISTENCIA_PRODUCTO` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Fabricante` VARCHAR(45) NOT NULL,
  `Codigo_Producto` VARCHAR(10) NOT NULL,
  `Existencia` INT NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `Codigo_Tienda` VARCHAR(10) NOT NULL,
  `Descripcion` VARCHAR(200) NULL,
  `Garantia` INT NULL,
  PRIMARY KEY (`Codigo_Producto`, `Codigo_Tienda`),
  INDEX `fk_EXISTENCIA_PRODUCTO_TIENDA1_idx` (`Codigo_Tienda` ASC) VISIBLE,
  CONSTRAINT `fk_EXISTENCIA_PRODUCTO_TIENDA1`
    FOREIGN KEY (`Codigo_Tienda`)
    REFERENCES `mydb`.`TIENDA` (`Codigo_Tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_PEDIDO` (
  `Id_DetallePedido` INT NOT NULL AUTO_INCREMENT,
  `Codigo_Pedido` INT NOT NULL,
  `Tienda_Origen` VARCHAR(10) NOT NULL,
  `Tienda_Destino` VARCHAR(10) NOT NULL,
  `Codigo_Producto` VARCHAR(10) NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio` DOUBLE NULL,
  `SubTotal` DOUBLE NOT NULL,
  `Tiempo_Tiendas` INT NULL,
  INDEX `fk_TIEMPO_has_PEDIDO_PEDIDO1_idx` (`Codigo_Pedido` ASC) VISIBLE,
  PRIMARY KEY (`Id_DetallePedido`),
  INDEX `fk_DETALLE_PEDIDO_EXISTENCIA_PRODUCTO1_idx` (`Codigo_Producto` ASC, `Tienda_Origen` ASC) VISIBLE,
  CONSTRAINT `Id_Pedido`
    FOREIGN KEY (`Codigo_Pedido`)
    REFERENCES `mydb`.`PEDIDO` (`Codigo_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_PEDIDO_EXISTENCIA_PRODUCTO1`
    FOREIGN KEY (`Codigo_Producto` , `Tienda_Origen`)
    REFERENCES `mydb`.`EXISTENCIA_PRODUCTO` (`Codigo_Producto` , `Codigo_Tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_VENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_VENTAS` (
  `Id_DetalleVentas` INT NOT NULL AUTO_INCREMENT,
  `Id_Ventas` INT NOT NULL,
  `Tienda_Existencia` VARCHAR(10) NOT NULL,
  `Codigo_Producto` VARCHAR(10) NOT NULL,
  `Cantidad_Venta` INT NULL,
  `Precio` DOUBLE NULL,
  `SubTotal` DOUBLE NULL,
  INDEX `fk_VENTAS_has_EXISTENCIA_VENTAS1_idx` (`Id_Ventas` ASC) VISIBLE,
  PRIMARY KEY (`Id_DetalleVentas`),
  INDEX `fk_DETALLE_VENTAS_EXISTENCIA_PRODUCTO1_idx` (`Codigo_Producto` ASC, `Tienda_Existencia` ASC) VISIBLE,
  CONSTRAINT `fk_VENTAS_has_EXISTENCIA_VENTAS1`
    FOREIGN KEY (`Id_Ventas`)
    REFERENCES `mydb`.`VENTAS` (`Id_Ventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_VENTAS_EXISTENCIA_PRODUCTO1`
    FOREIGN KEY (`Codigo_Producto` , `Tienda_Existencia`)
    REFERENCES `mydb`.`EXISTENCIA_PRODUCTO` (`Codigo_Producto` , `Codigo_Tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
